/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicRemoveMultipleCliniciansRequest {
    #[serde(rename = "ClinicianIds")]
    pub clinician_ids: Vec<i32>,
}

impl ClinicRemoveMultipleCliniciansRequest {
    pub fn new(clinician_ids: Vec<i32>) -> ClinicRemoveMultipleCliniciansRequest {
        ClinicRemoveMultipleCliniciansRequest {
            clinician_ids,
        }
    }
}

