/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoverageMessage {
    #[serde(rename = "Message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "LongMessage", skip_serializing_if = "Option::is_none")]
    pub long_message: Option<String>,
}

impl CoverageMessage {
    pub fn new() -> CoverageMessage {
        CoverageMessage {
            message: None,
            long_message: None,
        }
    }
}

