/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeaNumber {
    #[serde(rename = "DEANumber")]
    pub dea_number: String,
    #[serde(rename = "State", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "ClinicId", skip_serializing_if = "Option::is_none")]
    pub clinic_id: Option<String>,
}

impl DeaNumber {
    pub fn new(dea_number: String) -> DeaNumber {
        DeaNumber {
            dea_number,
            state: None,
            clinic_id: None,
        }
    }
}

