/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FreetextPatientAllergyRequest {
    #[serde(rename = "FreeTextDisplayName")]
    pub free_text_display_name: String,
    /// The patient reaction to the allergy.
    #[serde(rename = "Reaction", skip_serializing_if = "Option::is_none")]
    pub reaction: Option<String>,
    /// The allergy reaction type.
    #[serde(rename = "ReactionType")]
    pub reaction_type: ReactionType,
    /// The status of the allergy.
    #[serde(rename = "StatusType")]
    pub status_type: StatusType,
    /// The onset date of the allergy.
    #[serde(rename = "OnsetDate", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub onset_date: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl FreetextPatientAllergyRequest {
    pub fn new(free_text_display_name: String, reaction_type: ReactionType, status_type: StatusType) -> FreetextPatientAllergyRequest {
        FreetextPatientAllergyRequest {
            free_text_display_name,
            reaction: None,
            reaction_type,
            status_type,
            onset_date: None,
        }
    }
}
/// The allergy reaction type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReactionType {
    #[serde(rename = "Allergy")]
    Allergy,
    #[serde(rename = "AdverseReaction")]
    AdverseReaction,
}

impl Default for ReactionType {
    fn default() -> ReactionType {
        Self::Allergy
    }
}
/// The status of the allergy.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusType {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Deleted")]
    Deleted,
}

impl Default for StatusType {
    fn default() -> StatusType {
        Self::Active
    }
}

