/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

/// IdentifierGuidResponse : Represents a generic response containing an entity identifier.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifierGuidResponse {
    /// The entity identifier.
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl IdentifierGuidResponse {
    /// Represents a generic response containing an entity identifier.
    pub fn new() -> IdentifierGuidResponse {
        IdentifierGuidResponse {
            id: None,
            result: None,
        }
    }
}

