/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderSetFavorite {
    #[serde(rename = "DispensableDrugId", skip_serializing_if = "Option::is_none")]
    pub dispensable_drug_id: Option<crate::ids::DispensableDrugId>,
    #[serde(rename = "SupplyId", skip_serializing_if = "Option::is_none")]
    pub supply_id: Option<crate::ids::SupplyId>,
    #[serde(rename = "FreeText", skip_serializing_if = "Option::is_none")]
    pub free_text: Option<String>,
    #[serde(rename = "CompoundDescription", skip_serializing_if = "Option::is_none")]
    pub compound_description: Option<String>,
    #[serde(rename = "CompoundIngredients", skip_serializing_if = "Option::is_none")]
    pub compound_ingredients: Option<Vec<models::CompoundIngredient>>,
    #[serde(rename = "FavoriteId", skip_serializing_if = "Option::is_none")]
    pub favorite_id: Option<i32>,
    #[serde(rename = "Refills")]
    pub refills: i32,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "DispenseUnitTypeId")]
    pub dispense_unit_type_id: i32,
    #[serde(rename = "Quantity")]
    pub quantity: String,
    #[serde(rename = "NoSubstitutions", skip_serializing_if = "Option::is_none")]
    pub no_substitutions: Option<bool>,
    #[serde(rename = "Notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "Directions")]
    pub directions: String,
    #[serde(rename = "FirstPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub first_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
    #[serde(rename = "SecondPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub second_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
}

impl OrderSetFavorite {
    pub fn new(refills: i32, dispense_unit_type_id: i32, quantity: String, directions: String) -> OrderSetFavorite {
        OrderSetFavorite {
            dispensable_drug_id: None,
            supply_id: None,
            free_text: None,
            compound_description: None,
            compound_ingredients: None,
            favorite_id: None,
            refills,
            days_supply: None,
            dispense_unit_type_id,
            quantity,
            no_substitutions: None,
            notes: None,
            directions,
            first_prescription_diagnosis: None,
            second_prescription_diagnosis: None,
        }
    }
}

