/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayerAlternativeDetail {
    #[serde(rename = "Ndc", skip_serializing_if = "Option::is_none")]
    pub ndc: Option<String>,
    #[serde(rename = "Coverage", skip_serializing_if = "Option::is_none")]
    pub coverage: Option<Box<models::MedicationCoverage>>,
}

impl PayerAlternativeDetail {
    pub fn new() -> PayerAlternativeDetail {
        PayerAlternativeDetail {
            ndc: None,
            coverage: None,
        }
    }
}

