/*
 * DoseSpot REST API - Plan: Hybrid + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Hybrid_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelfReportedMedicationResponse {
    #[serde(rename = "SelfReportedMedicationId", skip_serializing_if = "Option::is_none")]
    pub self_reported_medication_id: Option<crate::ids::SelfReportedMedicationId>,
    #[serde(rename = "DateReported", skip_serializing_if = "Option::is_none")]
    pub date_reported: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "DatePrescribed", skip_serializing_if = "Option::is_none")]
    pub date_prescribed: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "DisplayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "DispenseUnitType", skip_serializing_if = "Option::is_none")]
    pub dispense_unit_type: Option<String>,
    #[serde(rename = "DosageText", skip_serializing_if = "Option::is_none")]
    pub dosage_text: Option<String>,
    #[serde(rename = "Directions", skip_serializing_if = "Option::is_none")]
    pub directions: Option<String>,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "Dispense", skip_serializing_if = "Option::is_none")]
    pub dispense: Option<String>,
    #[serde(rename = "Quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "DispenseUnitTypeId", skip_serializing_if = "Option::is_none")]
    pub dispense_unit_type_id: Option<i32>,
    #[serde(rename = "Refills", skip_serializing_if = "Option::is_none")]
    pub refills: Option<i32>,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "DiscontinuedDate", skip_serializing_if = "Option::is_none")]
    pub discontinued_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<i32>,
    #[serde(rename = "Encounter", skip_serializing_if = "Option::is_none")]
    pub encounter: Option<String>,
    #[serde(rename = "DispensableDrugID", skip_serializing_if = "Option::is_none")]
    pub dispensable_drug_id: Option<crate::ids::DispensableDrugId>,
    #[serde(rename = "RoutedDoseformDrugID", skip_serializing_if = "Option::is_none")]
    pub routed_doseform_drug_id: Option<i32>,
    #[serde(rename = "RoutedDoseFormDrugID", skip_serializing_if = "Option::is_none")]
    pub routed_dose_form_drug_id: Option<i32>,
    #[serde(rename = "OTC", skip_serializing_if = "Option::is_none")]
    pub otc: Option<bool>,
    #[serde(rename = "NDC", skip_serializing_if = "Option::is_none")]
    pub ndc: Option<String>,
    #[serde(rename = "DoseForm", skip_serializing_if = "Option::is_none")]
    pub dose_form: Option<String>,
    #[serde(rename = "Route", skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,
    #[serde(rename = "Strength", skip_serializing_if = "Option::is_none")]
    pub strength: Option<String>,
}

impl SelfReportedMedicationResponse {
    pub fn new() -> SelfReportedMedicationResponse {
        SelfReportedMedicationResponse {
            self_reported_medication_id: None,
            date_reported: None,
            date_prescribed: None,
            display_name: None,
            dispense_unit_type: None,
            dosage_text: None,
            directions: None,
            days_supply: None,
            dispense: None,
            quantity: None,
            dispense_unit_type_id: None,
            refills: None,
            comment: None,
            status: None,
            discontinued_date: None,
            schedule: None,
            encounter: None,
            dispensable_drug_id: None,
            routed_doseform_drug_id: None,
            routed_dose_form_drug_id: None,
            otc: None,
            ndc: None,
            dose_form: None,
            route: None,
            strength: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Discontinued")]
    Discontinued,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "CancelPending")]
    CancelPending,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Changed")]
    Changed,
    #[serde(rename = "FullFill")]
    FullFill,
    #[serde(rename = "PartialFill")]
    PartialFill,
    #[serde(rename = "NoFill")]
    NoFill,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}

