/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::full::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clinicians_accept_agreement_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansAcceptAgreementV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_accept_identity_proofing_disclaimer_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansAcceptIdentityProofingDisclaimerV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_add_supervisor_to_clinician_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansAddSupervisorToClinicianV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_change_pin_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansChangePinV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_clinician_add_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansClinicianAddV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_clinician_check_registration_status_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansClinicianCheckRegistrationStatusV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_clinician_identity_proofing_answers_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansClinicianIdentityProofingAnswersV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_clinician_identity_proofing_one_time_code_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansClinicianIdentityProofingOneTimeCodeV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_clinician_identity_proofing_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansClinicianIdentityProofingV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_delete_supervisor_to_clinician_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansDeleteSupervisorToClinicianV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_clinician_by_npi_or_dea_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetClinicianByNpiOrDeaV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_clinician_details_by_id_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetClinicianDetailsByIdV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_clinician_legal_agreements_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetClinicianLegalAgreementsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_clinician_pdmpv2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetClinicianPdmpv2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_identity_proofing_disclaimer_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetIdentityProofingDisclaimerV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_patient_clinicians_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetPatientCliniciansV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_get_prescription_prescriber_info_apiv2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansGetPrescriptionPrescriberInfoApiv2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_initialize_idpv2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansInitializeIdpv2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_put_clinician_edit_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansPutClinicianEditV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_reset_clinician_pin_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansResetClinicianPinV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_reset_my_pin_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansResetMyPinV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinicians_set_pin_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CliniciansSetPinV2Error {
    UnknownValue(serde_json::Value),
}


pub async fn clinicians_accept_agreement_v2(configuration: &configuration::Configuration, request: models::ClinicianAcceptAgreementRequest) -> Result<models::ClinicianAcceptAgreementResponse, Error<CliniciansAcceptAgreementV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/acceptAgreement", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianAcceptAgreementResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianAcceptAgreementResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansAcceptAgreementV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Completes the signing of the disclaimer for identity proofing for a clinician.
pub async fn clinicians_accept_identity_proofing_disclaimer_v2(configuration: &configuration::Configuration, request: models::ClinicianIdentityProofingDisclaimerRequest) -> Result<models::ClinicianIdentityProofingDisclaimerResponse, Error<CliniciansAcceptIdentityProofingDisclaimerV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/idpDisclaimer", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianIdentityProofingDisclaimerResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianIdentityProofingDisclaimerResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansAcceptIdentityProofingDisclaimerV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_add_supervisor_to_clinician_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, request: Vec<models::SupervisorToClinicianRequest>) -> Result<models::Response, Error<CliniciansAddSupervisorToClinicianV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/supervisors", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansAddSupervisorToClinicianV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_change_pin_v2(configuration: &configuration::Configuration, request: models::ClinicianChangePinRequest) -> Result<models::Response, Error<CliniciansChangePinV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/pin", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansChangePinV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new clinician
pub async fn clinicians_clinician_add_v2(configuration: &configuration::Configuration, request: models::AddEditClinicianRequest) -> Result<models::IdentifierResponse, Error<CliniciansClinicianAddV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansClinicianAddV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a clinician’s registration status at the clinic used to obtain the Authentication token
pub async fn clinicians_clinician_check_registration_status_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId) -> Result<models::ItemResponseeRxRegistrationStatusType, Error<CliniciansClinicianCheckRegistrationStatusV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/registrationStatus", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ItemResponseeRxRegistrationStatusType`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ItemResponseeRxRegistrationStatusType`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansClinicianCheckRegistrationStatusV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Completes the final step of identity proofing for a clinician. This must be completed along with subsequent steps to enable electronic   prescribing of controlled substances by this clinician.If an additional question is returned, this same method must be used again to   submit an answer for it. After this, a clinician will either be marked as having passed or failed identity proofing.
pub async fn clinicians_clinician_identity_proofing_answers_v2(configuration: &configuration::Configuration, request: models::ClinicianIdentityProofingAnswersRequest) -> Result<models::ClinicianIdentityProofingResponse, Error<CliniciansClinicianIdentityProofingAnswersV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/idpAnswers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansClinicianIdentityProofingAnswersV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Identity Proofing with a one time code
pub async fn clinicians_clinician_identity_proofing_one_time_code_v2(configuration: &configuration::Configuration, request: models::ClinicianIdentityProofingOneTimeCodeRequest) -> Result<models::ClinicianIdentityProofingResponse, Error<CliniciansClinicianIdentityProofingOneTimeCodeV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/idpOtp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansClinicianIdentityProofingOneTimeCodeV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Completes the first step of identity proofing for a clinician. This must be completed along with subsequent steps in   order to enable electronic prescribing of controlled substances by this clinician. The results will return a session   ID and a collection of questions and answers (3 sets of 4 answers), which can be used as the body parameters for the   second step of IDP
pub async fn clinicians_clinician_identity_proofing_v2(configuration: &configuration::Configuration, request: models::ClinicianIdentityProofingRequest) -> Result<models::ClinicianIdentityProofingResponse, Error<CliniciansClinicianIdentityProofingV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/idp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianIdentityProofingResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansClinicianIdentityProofingV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_delete_supervisor_to_clinician_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, request: models::DeleteClinicianSupervisorRequest) -> Result<models::Response, Error<CliniciansDeleteSupervisorToClinicianV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/supervisors", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansDeleteSupervisorToClinicianV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_get_clinician_by_npi_or_dea_v2(configuration: &configuration::Configuration, npi: Option<&str>, dea: Option<&str>) -> Result<models::IdentifierResponse, Error<CliniciansGetClinicianByNpiOrDeaV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_npi = npi;
    let p_query_dea = dea;

    let uri_str = format!("{}/api/clinician", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_npi {
        req_builder = req_builder.query(&[("npi", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_dea {
        req_builder = req_builder.query(&[("dea", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetClinicianByNpiOrDeaV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Clinician's details By ID
pub async fn clinicians_get_clinician_details_by_id_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId) -> Result<models::ItemResponseClinician, Error<CliniciansGetClinicianDetailsByIdV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;

    let uri_str = format!("{}/api/clinicians/{clinicianId}", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ItemResponseClinician`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ItemResponseClinician`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetClinicianDetailsByIdV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_get_clinician_legal_agreements_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId) -> Result<models::ListResponseAgreementInfoResponse, Error<CliniciansGetClinicianLegalAgreementsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/legalAgreements", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseAgreementInfoResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseAgreementInfoResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetClinicianLegalAgreementsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Prescription Drug Monitoring Program data for the clinician's state
pub async fn clinicians_get_clinician_pdmpv2(configuration: &configuration::Configuration, ) -> Result<models::ItemResponsePdmpResponse, Error<CliniciansGetClinicianPdmpv2Error>> {

    let uri_str = format!("{}/api/clinicians/pdmp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ItemResponsePdmpResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ItemResponsePdmpResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetClinicianPdmpv2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves the signing of the disclaimer for identity proofing for a clinician. If you have signed the disclaimer, there will be a date.
pub async fn clinicians_get_identity_proofing_disclaimer_v2(configuration: &configuration::Configuration, ) -> Result<models::ClinicianIdentityProofingDisclaimerResponse, Error<CliniciansGetIdentityProofingDisclaimerV2Error>> {

    let uri_str = format!("{}/api/clinicians/idpDisclaimer", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicianIdentityProofingDisclaimerResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicianIdentityProofingDisclaimerResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetIdentityProofingDisclaimerV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information on all clinicians that have affected a patient record
pub async fn clinicians_get_patient_clinicians_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::ListResponseClinician, Error<CliniciansGetPatientCliniciansV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/clinicians", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseClinician`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseClinician`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetPatientCliniciansV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_get_prescription_prescriber_info_apiv2(configuration: &configuration::Configuration, prescription_id: crate::ids::PrescriptionId) -> Result<models::PrescriberInfoResponse, Error<CliniciansGetPrescriptionPrescriberInfoApiv2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prescription_id = prescription_id;

    let uri_str = format!("{}/api/prescriptions/{prescriptionId}/prescriberInfo", configuration.base_path, prescriptionId=p_path_prescription_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PrescriberInfoResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PrescriberInfoResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansGetPrescriptionPrescriberInfoApiv2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mark Clinician IDP Initialized
pub async fn clinicians_initialize_idpv2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId) -> Result<models::Response, Error<CliniciansInitializeIdpv2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/idpInit", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansInitializeIdpv2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing clinician’s contact information
pub async fn clinicians_put_clinician_edit_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, request: models::AddEditClinicianRequest) -> Result<models::Response, Error<CliniciansPutClinicianEditV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/{clinicianId}", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansPutClinicianEditV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Resets a different clinician's PIN to \"\" or null
pub async fn clinicians_reset_clinician_pin_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId) -> Result<models::Response, Error<CliniciansResetClinicianPinV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/resetPin", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansResetClinicianPinV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Resets the clinician's PIN to \"\" or null
pub async fn clinicians_reset_my_pin_v2(configuration: &configuration::Configuration, ) -> Result<models::Response, Error<CliniciansResetMyPinV2Error>> {

    let uri_str = format!("{}/api/clinicians/resetPin", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansResetMyPinV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinicians_set_pin_v2(configuration: &configuration::Configuration, request: models::ClinicianSetPinRequest) -> Result<models::Response, Error<CliniciansSetPinV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/pin", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CliniciansSetPinV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

