/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clinics_get_clinic_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetClinicDetailsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_get_clinician_clinics_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetClinicianClinicsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_get_patient_clinics_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetPatientClinicsV2Error {
    UnknownValue(serde_json::Value),
}


/// Given a clinicId gets the respective clinic’s information
pub async fn clinics_get_clinic_details_v2(configuration: &configuration::Configuration, clinic_id: crate::ids::ClinicId) -> Result<models::ClinicDetailResponse, Error<ClinicsGetClinicDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinic_id = clinic_id;

    let uri_str = format!("{}/api/clinics/{clinicId}", configuration.base_path, clinicId=p_path_clinic_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicDetailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicDetailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetClinicDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a list of clinic identifiers for a clinician  regardless of eRx functions for those clinics
pub async fn clinics_get_clinician_clinics_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, include_clinic_groups: Option<bool>, clinic_status: Option<&str>) -> Result<models::ListResponseClinicIdentifier, Error<ClinicsGetClinicianClinicsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_query_include_clinic_groups = include_clinic_groups;
    let p_query_clinic_status = clinic_status;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/clinicIds", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include_clinic_groups {
        req_builder = req_builder.query(&[("includeClinicGroups", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_clinic_status {
        req_builder = req_builder.query(&[("clinicStatus", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseClinicIdentifier`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseClinicIdentifier`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetClinicianClinicsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information on all clinics that have been associated with a patient
pub async fn clinics_get_patient_clinics_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::ListResponseClinic, Error<ClinicsGetPatientClinicsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/clinics", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseClinic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseClinic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetPatientClinicsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

