/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clinician_order_sets_get_clinician_order_set_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicianOrderSetsGetClinicianOrderSetDetailsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinician_order_sets_get_clinician_order_sets_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicianOrderSetsGetClinicianOrderSetsV2Error {
    UnknownValue(serde_json::Value),
}


pub async fn clinician_order_sets_get_clinician_order_set_details_v2(configuration: &configuration::Configuration, order_set_id: crate::ids::OrderSetId) -> Result<models::OrderSetDetailsResponse, Error<ClinicianOrderSetsGetClinicianOrderSetDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_order_set_id = order_set_id;

    let uri_str = format!("{}/api/clinicians/ordersets/{orderSetId}/details", configuration.base_path, orderSetId=p_path_order_set_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderSetDetailsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderSetDetailsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicianOrderSetsGetClinicianOrderSetDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clinician_order_sets_get_clinician_order_sets_v2(configuration: &configuration::Configuration, page_number: Option<i32>, page_size: Option<i32>, sort_order: Option<&str>, search_string: Option<&str>) -> Result<models::PagedListResponseOrderSetResponse, Error<ClinicianOrderSetsGetClinicianOrderSetsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page_number = page_number;
    let p_query_page_size = page_size;
    let p_query_sort_order = sort_order;
    let p_query_search_string = search_string;

    let uri_str = format!("{}/api/clinicians/ordersets", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_string {
        req_builder = req_builder.query(&[("searchString", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseOrderSetResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseOrderSetResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicianOrderSetsGetClinicianOrderSetsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

