/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`pharmacies_get_patient_pharmacies_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PharmaciesGetPatientPharmaciesV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`pharmacies_get_pharmacy_restrictions_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PharmaciesGetPharmacyRestrictionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`pharmacies_get_pharmacy_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PharmaciesGetPharmacyV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`pharmacies_pharmacy_search_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PharmaciesPharmacySearchV2Error {
    UnknownValue(serde_json::Value),
}


/// Retrieves a detailed list of a preferred pharmacies in the patient’s record
pub async fn pharmacies_get_patient_pharmacies_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::ListResponsePatientPharmacy, Error<PharmaciesGetPatientPharmaciesV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/pharmacies", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponsePatientPharmacy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponsePatientPharmacy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PharmaciesGetPatientPharmaciesV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a list of a preferred pharmacies given  a Dispensable Drug ID
pub async fn pharmacies_get_pharmacy_restrictions_v2(configuration: &configuration::Configuration, dispensable_drug_id: crate::ids::DispensableDrugId, page_number: Option<i32>) -> Result<models::PagedListResponsePharmacy, Error<PharmaciesGetPharmacyRestrictionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_dispensable_drug_id = dispensable_drug_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/pharmacies/restrictions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("dispensableDrugId", &p_query_dispensable_drug_id.to_string())]);
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponsePharmacy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponsePharmacy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PharmaciesGetPharmacyRestrictionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves key data about a single pharmacy on the Surescripts ePrescribing network
pub async fn pharmacies_get_pharmacy_v2(configuration: &configuration::Configuration, pharmacy_id: crate::ids::PharmacyId) -> Result<models::ItemResponsePharmacy, Error<PharmaciesGetPharmacyV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_pharmacy_id = pharmacy_id;

    let uri_str = format!("{}/api/pharmacies/{pharmacyId}", configuration.base_path, pharmacyId=p_path_pharmacy_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ItemResponsePharmacy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ItemResponsePharmacy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PharmaciesGetPharmacyV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of pharmacies matching the specified search parameters
pub async fn pharmacies_pharmacy_search_v2(configuration: &configuration::Configuration, name: Option<&str>, city: Option<&str>, state: Option<&str>, zip: Option<&str>, address: Option<&str>, phone_or_fax: Option<&str>, specialty: Option<Vec<String>>, ncpdp_id: Option<&str>, page_number: Option<i32>) -> Result<models::PagedListResponsePharmacy, Error<PharmaciesPharmacySearchV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_name = name;
    let p_query_city = city;
    let p_query_state = state;
    let p_query_zip = zip;
    let p_query_address = address;
    let p_query_phone_or_fax = phone_or_fax;
    let p_query_specialty = specialty;
    let p_query_ncpdp_id = ncpdp_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/pharmacies/search", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_city {
        req_builder = req_builder.query(&[("city", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_zip {
        req_builder = req_builder.query(&[("zip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_address {
        req_builder = req_builder.query(&[("address", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_phone_or_fax {
        req_builder = req_builder.query(&[("phoneOrFax", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_specialty {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("specialty".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("specialty", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ncpdp_id {
        req_builder = req_builder.query(&[("ncpdpId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponsePharmacy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponsePharmacy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PharmaciesPharmacySearchV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

