/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`prescriptions_get_patient_prescription_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrescriptionsGetPatientPrescriptionV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`prescriptions_get_patient_prescriptions_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrescriptionsGetPatientPrescriptionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`prescriptions_get_prescription_log_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrescriptionsGetPrescriptionLogDetailsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`prescriptions_get_prescription_snapshot_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrescriptionsGetPrescriptionSnapshotV2Error {
    UnknownValue(serde_json::Value),
}


/// Retrieves details of a prescription in a patient record
pub async fn prescriptions_get_patient_prescription_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, prescription_id: crate::ids::PrescriptionId) -> Result<models::PrescriptionResponse, Error<PrescriptionsGetPatientPrescriptionV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_prescription_id = prescription_id;

    let uri_str = format!("{}/api/patients/{patientId}/prescriptions/{prescriptionId}", configuration.base_path, patientId=p_path_patient_id, prescriptionId=p_path_prescription_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PrescriptionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PrescriptionResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PrescriptionsGetPatientPrescriptionV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves details of prescriptions in a patient record
pub async fn prescriptions_get_patient_prescriptions_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, end_date: Option<chrono::DateTime<chrono::FixedOffset>>, start_date: Option<chrono::DateTime<chrono::FixedOffset>>, status_class: Option<&str>, prescription_status: Option<&str>, page_number: Option<i32>, sort_column: Option<&str>, sort_order: Option<&str>) -> Result<models::PagedListResponsePrescription, Error<PrescriptionsGetPatientPrescriptionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_query_end_date = end_date;
    let p_query_start_date = start_date;
    let p_query_status_class = status_class;
    let p_query_prescription_status = prescription_status;
    let p_query_page_number = page_number;
    let p_query_sort_column = sort_column;
    let p_query_sort_order = sort_order;

    let uri_str = format!("{}/api/patients/{patientId}/prescriptions", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("endDate", &param_value.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))]);
    }
    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("startDate", &param_value.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))]);
    }
    if let Some(ref param_value) = p_query_status_class {
        req_builder = req_builder.query(&[("statusClass", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prescription_status {
        req_builder = req_builder.query(&[("prescriptionStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_column {
        req_builder = req_builder.query(&[("sortColumn", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponsePrescription`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponsePrescription`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PrescriptionsGetPatientPrescriptionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves the prescription log for an existing prescription in a patient record. This is the full history of the prescription.
pub async fn prescriptions_get_prescription_log_details_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, prescription_id: crate::ids::PrescriptionId) -> Result<models::ListResponsePrescriptionLog, Error<PrescriptionsGetPrescriptionLogDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_prescription_id = prescription_id;

    let uri_str = format!("{}/api/patients/{patientId}/prescriptions/{prescriptionId}/log", configuration.base_path, patientId=p_path_patient_id, prescriptionId=p_path_prescription_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponsePrescriptionLog`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponsePrescriptionLog`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PrescriptionsGetPrescriptionLogDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves prescription snapshot
pub async fn prescriptions_get_prescription_snapshot_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, prescription_id: crate::ids::PrescriptionId) -> Result<models::PrescriptionSnapshotResponse, Error<PrescriptionsGetPrescriptionSnapshotV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_prescription_id = prescription_id;

    let uri_str = format!("{}/api/patients/{patientId}/prescriptions/{prescriptionId}/snapshot", configuration.base_path, patientId=p_path_patient_id, prescriptionId=p_path_prescription_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PrescriptionSnapshotResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PrescriptionSnapshotResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PrescriptionsGetPrescriptionSnapshotV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

