/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`prior_authorizations_get_prior_authorization_status_log_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PriorAuthorizationsGetPriorAuthorizationStatusLogV2Error {
    UnknownValue(serde_json::Value),
}


/// Status Log for Specific Prior Authorization Case By Id
pub async fn prior_authorizations_get_prior_authorization_status_log_v2(configuration: &configuration::Configuration, prior_auth_id: crate::ids::PriorAuthId) -> Result<models::PriorAuthorizationStatusLogUiResponse, Error<PriorAuthorizationsGetPriorAuthorizationStatusLogV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_prior_auth_id = prior_auth_id;

    let uri_str = format!("{}/api/priorAuths/{priorAuthId}/statusLog", configuration.base_path, priorAuthId=p_path_prior_auth_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PriorAuthorizationStatusLogUiResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PriorAuthorizationStatusLogUiResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PriorAuthorizationsGetPriorAuthorizationStatusLogV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

