/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::readonly::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`rx_changes_get_rx_change_queue_detailed_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RxChangesGetRxChangeQueueDetailedV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rx_changes_get_rx_change_queue_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RxChangesGetRxChangeQueueV2Error {
    UnknownValue(serde_json::Value),
}


/// Lists the number of notifications for pending RxChange requests associated with clinician's clinic(s)/patient.  Includes detailed prescription information.
pub async fn rx_changes_get_rx_change_queue_detailed_v2(configuration: &configuration::Configuration, clinic: Option<&str>, patient_id: Option<crate::ids::PatientId>, page_number: Option<i32>) -> Result<models::PagedListResponseGetRxChangeDetailedResponse, Error<RxChangesGetRxChangeQueueDetailedV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_clinic = clinic;
    let p_query_patient_id = patient_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/rxchanges/pending/detailed", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_clinic {
        req_builder = req_builder.query(&[("clinic", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_patient_id {
        req_builder = req_builder.query(&[("patientId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseGetRxChangeDetailedResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseGetRxChangeDetailedResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RxChangesGetRxChangeQueueDetailedV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists the number of notifications for pending RxChange requests associated with clinician's clinic(s)/patient
pub async fn rx_changes_get_rx_change_queue_v2(configuration: &configuration::Configuration, clinic: Option<&str>, patient_id: Option<crate::ids::PatientId>, page_number: Option<i32>) -> Result<models::PagedListResponseGetRxChangeResponse, Error<RxChangesGetRxChangeQueueV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_clinic = clinic;
    let p_query_patient_id = patient_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/rxchanges/pending", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_clinic {
        req_builder = req_builder.query(&[("clinic", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_patient_id {
        req_builder = req_builder.query(&[("patientId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseGetRxChangeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseGetRxChangeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RxChangesGetRxChangeQueueV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

