/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::jumpstart_epcs::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clinics_clinic_add_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsClinicAddV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_clinic_edit_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsClinicEditV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_clinic_remove_multiple_clinicians_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsClinicRemoveMultipleCliniciansV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_clinician_add_multiple_clinics_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsClinicianAddMultipleClinicsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_get_clinic_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetClinicDetailsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_get_clinician_clinics_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetClinicianClinicsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_get_patient_clinics_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsGetPatientClinicsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clinics_patient_clinic_transfer_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicsPatientClinicTransferV2Error {
    UnknownValue(serde_json::Value),
}


/// Adds a new clinic
pub async fn clinics_clinic_add_v2(configuration: &configuration::Configuration, request: models::AddEditClinicRequest) -> Result<models::ClinicKeyResponse, Error<ClinicsClinicAddV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicKeyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicKeyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsClinicAddV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing clinic’s contact information
pub async fn clinics_clinic_edit_v2(configuration: &configuration::Configuration, clinic_id: crate::ids::ClinicId, request: models::AddEditClinicRequest) -> Result<models::Response, Error<ClinicsClinicEditV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinic_id = clinic_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinics/{clinicId}", configuration.base_path, clinicId=p_path_clinic_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsClinicEditV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Removes an array of clinicians from a specified clinic
pub async fn clinics_clinic_remove_multiple_clinicians_v2(configuration: &configuration::Configuration, clinic_id: crate::ids::ClinicId, request: models::ClinicRemoveMultipleCliniciansRequest) -> Result<Vec<models::Response>, Error<ClinicsClinicRemoveMultipleCliniciansV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinic_id = clinic_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinics/{clinicId}/clinicians", configuration.base_path, clinicId=p_path_clinic_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Response&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Response&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsClinicRemoveMultipleCliniciansV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Adds a clinician to one or more existing clinics
pub async fn clinics_clinician_add_multiple_clinics_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, request: models::ClinicianAddMultipleClinicsRequest) -> Result<Vec<models::Response>, Error<ClinicsClinicianAddMultipleClinicsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/clinics", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Response&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Response&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsClinicianAddMultipleClinicsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Given a clinicId gets the respective clinic’s information
pub async fn clinics_get_clinic_details_v2(configuration: &configuration::Configuration, clinic_id: crate::ids::ClinicId) -> Result<models::ClinicDetailResponse, Error<ClinicsGetClinicDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinic_id = clinic_id;

    let uri_str = format!("{}/api/clinics/{clinicId}", configuration.base_path, clinicId=p_path_clinic_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClinicDetailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClinicDetailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetClinicDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a list of clinic identifiers for a clinician  regardless of eRx functions for those clinics
pub async fn clinics_get_clinician_clinics_v2(configuration: &configuration::Configuration, clinician_id: crate::ids::ClinicianId, include_clinic_groups: Option<bool>, clinic_status: Option<&str>) -> Result<models::ListResponseClinicIdentifier, Error<ClinicsGetClinicianClinicsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_clinician_id = clinician_id;
    let p_query_include_clinic_groups = include_clinic_groups;
    let p_query_clinic_status = clinic_status;

    let uri_str = format!("{}/api/clinicians/{clinicianId}/clinicIds", configuration.base_path, clinicianId=p_path_clinician_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include_clinic_groups {
        req_builder = req_builder.query(&[("includeClinicGroups", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_clinic_status {
        req_builder = req_builder.query(&[("clinicStatus", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseClinicIdentifier`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseClinicIdentifier`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetClinicianClinicsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information on all clinics that have been associated with a patient
pub async fn clinics_get_patient_clinics_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::ListResponseClinic, Error<ClinicsGetPatientClinicsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/clinics", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponseClinic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponseClinic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsGetPatientClinicsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Change the clinic this patient is associated with
pub async fn clinics_patient_clinic_transfer_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, change_clinic_request: models::ChangePatientClinicRequest) -> Result<models::Response, Error<ClinicsPatientClinicTransferV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_change_clinic_request = change_clinic_request;

    let uri_str = format!("{}/api/patients/{patientId}/transfer", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_change_clinic_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicsPatientClinicTransferV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

