/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::jumpstart_epcs::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`notifications_get_prescriber_notification_counts_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NotificationsGetPrescriberNotificationCountsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`notifications_get_transmission_error_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NotificationsGetTransmissionErrorDetailsV2Error {
    UnknownValue(serde_json::Value),
}


/// Lists the number of notifications for refill requests, transmission errors, and prescriptions that are pending a response from the clinician at a single clinic
pub async fn notifications_get_prescriber_notification_counts_v2(configuration: &configuration::Configuration, ) -> Result<models::PrescriberNotificationCountsResponse, Error<NotificationsGetPrescriberNotificationCountsV2Error>> {

    let uri_str = format!("{}/api/notifications/counts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PrescriberNotificationCountsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PrescriberNotificationCountsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NotificationsGetPrescriberNotificationCountsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lists the notifications for transmission errors for the clinician's associated clinic(s)
pub async fn notifications_get_transmission_error_details_v2(configuration: &configuration::Configuration, page_number: Option<i32>, clinic: Option<&str>) -> Result<models::PagedListResponseTransmissionErrors, Error<NotificationsGetTransmissionErrorDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page_number = page_number;
    let p_query_clinic = clinic;

    let uri_str = format!("{}/api/notifications/errors", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_clinic {
        req_builder = req_builder.query(&[("clinic", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseTransmissionErrors`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseTransmissionErrors`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NotificationsGetTransmissionErrorDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

