/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::jumpstart_epcs::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`self_reported_medications_add_self_reported_medication_coded_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsAddSelfReportedMedicationCodedV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_add_self_reported_medication_free_text_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsAddSelfReportedMedicationFreeTextV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_add_self_reported_medication_simple_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsAddSelfReportedMedicationSimpleV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_edit_self_reported_medication_coded_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsEditSelfReportedMedicationCodedV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_edit_self_reported_medication_free_text_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsEditSelfReportedMedicationFreeTextV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_edit_self_reported_medication_simple_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsEditSelfReportedMedicationSimpleV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_get_patient_self_report_medication_details_by_id_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsGetPatientSelfReportMedicationDetailsByIdV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_get_patient_self_report_medications_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsGetPatientSelfReportMedicationsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`self_reported_medications_update_self_reported_medication_status_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SelfReportedMedicationsUpdateSelfReportedMedicationStatusV2Error {
    UnknownValue(serde_json::Value),
}


/// Adds a coded self-reported medication to a patient’s record
pub async fn self_reported_medications_add_self_reported_medication_coded_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, request: models::CodedSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsAddSelfReportedMedicationCodedV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/coded", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsAddSelfReportedMedicationCodedV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Adds a free-text self-reported medication to a patient’s record meaning the clinician can type any 300 character name.  This should only be used if a simple or coded version of the medication does not exist
pub async fn self_reported_medications_add_self_reported_medication_free_text_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, request: models::FreeTextSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsAddSelfReportedMedicationFreeTextV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/freetext", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsAddSelfReportedMedicationFreeTextV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Adds a simple self-reported medication to a patient’s record
pub async fn self_reported_medications_add_self_reported_medication_simple_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, request: models::SimpleSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsAddSelfReportedMedicationSimpleV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/simple", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsAddSelfReportedMedicationSimpleV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing self-reported medication in a patient record
pub async fn self_reported_medications_edit_self_reported_medication_coded_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, self_reported_medication_id: crate::ids::SelfReportedMedicationId, request: models::CodedSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsEditSelfReportedMedicationCodedV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_self_reported_medication_id = self_reported_medication_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/coded/{selfReportedMedicationId}", configuration.base_path, patientId=p_path_patient_id, selfReportedMedicationId=p_path_self_reported_medication_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsEditSelfReportedMedicationCodedV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing self-reported medication specified by a free-text DisplayName in a patient’s record
pub async fn self_reported_medications_edit_self_reported_medication_free_text_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, self_reported_medication_id: crate::ids::SelfReportedMedicationId, request: models::FreeTextSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsEditSelfReportedMedicationFreeTextV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_self_reported_medication_id = self_reported_medication_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/freetext/{selfReportedMedicationId}", configuration.base_path, patientId=p_path_patient_id, selfReportedMedicationId=p_path_self_reported_medication_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsEditSelfReportedMedicationFreeTextV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing simple self-reported medication in a patient record
pub async fn self_reported_medications_edit_self_reported_medication_simple_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, self_reported_medication_id: crate::ids::SelfReportedMedicationId, request: models::SimpleSelfReportedMedicationRequest) -> Result<models::IdentifierResponse, Error<SelfReportedMedicationsEditSelfReportedMedicationSimpleV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_self_reported_medication_id = self_reported_medication_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/simple/{selfReportedMedicationId}", configuration.base_path, patientId=p_path_patient_id, selfReportedMedicationId=p_path_self_reported_medication_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsEditSelfReportedMedicationSimpleV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves details of self-reported medication in a patient record by SelfReportedMedicationId
pub async fn self_reported_medications_get_patient_self_report_medication_details_by_id_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, self_reported_medication_id: crate::ids::SelfReportedMedicationId) -> Result<models::ItemResponseSelfReportedMedicationResponse, Error<SelfReportedMedicationsGetPatientSelfReportMedicationDetailsByIdV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_self_reported_medication_id = self_reported_medication_id;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/{selfReportedMedicationId}", configuration.base_path, patientId=p_path_patient_id, selfReportedMedicationId=p_path_self_reported_medication_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ItemResponseSelfReportedMedicationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ItemResponseSelfReportedMedicationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsGetPatientSelfReportMedicationDetailsByIdV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves details of self-reported medications in a patient record
pub async fn self_reported_medications_get_patient_self_report_medications_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, start_date: Option<chrono::DateTime<chrono::FixedOffset>>, end_date: Option<chrono::DateTime<chrono::FixedOffset>>, page_number: Option<i32>) -> Result<models::PagedListResponseSelfReportedMedicationResponse, Error<SelfReportedMedicationsGetPatientSelfReportMedicationsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("startDate", &param_value.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("endDate", &param_value.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseSelfReportedMedicationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseSelfReportedMedicationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsGetPatientSelfReportMedicationsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates the status of a self-reported medication in a patient’s record
pub async fn self_reported_medications_update_self_reported_medication_status_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, self_reported_medication_id: crate::ids::SelfReportedMedicationId, request: models::UpdateSelfReportedMedicationStatusRequest) -> Result<models::Response, Error<SelfReportedMedicationsUpdateSelfReportedMedicationStatusV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_self_reported_medication_id = self_reported_medication_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/selfReportedMedications/{selfReportedMedicationId}/updateStatus", configuration.base_path, patientId=p_path_patient_id, selfReportedMedicationId=p_path_self_reported_medication_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SelfReportedMedicationsUpdateSelfReportedMedicationStatusV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

