/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianAcceptAgreementResponse {
    #[serde(rename = "AgreementId", skip_serializing_if = "Option::is_none")]
    pub agreement_id: Option<i32>,
    #[serde(rename = "NameSigned", skip_serializing_if = "Option::is_none")]
    pub name_signed: Option<String>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ClinicianAcceptAgreementResponse {
    pub fn new() -> ClinicianAcceptAgreementResponse {
        ClinicianAcceptAgreementResponse {
            agreement_id: None,
            name_signed: None,
            result: None,
        }
    }
}

