/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFavoritesRequest {
    #[serde(rename = "FavoriteType", skip_serializing_if = "Option::is_none")]
    pub favorite_type: Option<FavoriteType>,
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    #[serde(rename = "PageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "SearchName", skip_serializing_if = "Option::is_none")]
    pub search_name: Option<String>,
}

impl GetFavoritesRequest {
    pub fn new() -> GetFavoritesRequest {
        GetFavoritesRequest {
            favorite_type: None,
            page_number: None,
            page_size: None,
            search_name: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FavoriteType {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "Medication")]
    Medication,
    #[serde(rename = "Supply")]
    Supply,
    #[serde(rename = "CompiledCompound")]
    CompiledCompound,
}

impl Default for FavoriteType {
    fn default() -> FavoriteType {
        Self::All
    }
}

