/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

/// ListResponsePatientAllergy : Represents a generic response containing a list of objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponsePatientAllergy {
    /// The list of elements to return.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::PatientAllergy>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ListResponsePatientAllergy {
    /// Represents a generic response containing a list of objects.
    pub fn new() -> ListResponsePatientAllergy {
        ListResponsePatientAllergy {
            items: None,
            result: None,
        }
    }
}

