/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaAppealDetails {
    #[serde(rename = "AppealCaseId", skip_serializing_if = "Option::is_none")]
    pub appeal_case_id: Option<String>,
    #[serde(rename = "NotesForAppeal", skip_serializing_if = "Option::is_none")]
    pub notes_for_appeal: Option<String>,
    #[serde(rename = "AppealReason", skip_serializing_if = "Option::is_none")]
    pub appeal_reason: Option<String>,
}

impl PaAppealDetails {
    pub fn new() -> PaAppealDetails {
        PaAppealDetails {
            appeal_case_id: None,
            notes_for_appeal: None,
            appeal_reason: None,
        }
    }
}

