/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaAnsweredQuestions {
    #[serde(rename = "Question", skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    #[serde(rename = "Answers", skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<models::PaAnswers>>,
}

impl PaAnsweredQuestions {
    pub fn new() -> PaAnsweredQuestions {
        PaAnsweredQuestions {
            question: None,
            answers: None,
        }
    }
}

