/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PharmacySearchRequest {
    /// Pharmacy name
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// City
    #[serde(rename = "City", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// State
    #[serde(rename = "State", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// ZIP code
    #[serde(rename = "Zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    /// Street address
    #[serde(rename = "Address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Phone or fax number
    #[serde(rename = "PhoneOrFax", skip_serializing_if = "Option::is_none")]
    pub phone_or_fax: Option<String>,
    /// Array of pharmacy specialty types to filter the search.
    #[serde(rename = "Specialty", skip_serializing_if = "Option::is_none")]
    pub specialty: Option<Vec<Specialty>>,
    /// NCPDP identifier for the pharmacy.
    #[serde(rename = "NcpdpId", skip_serializing_if = "Option::is_none")]
    pub ncpdp_id: Option<String>,
    /// Page number for paginated search results. Defaults to 1.
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
}

impl PharmacySearchRequest {
    pub fn new() -> PharmacySearchRequest {
        PharmacySearchRequest {
            name: None,
            city: None,
            state: None,
            zip: None,
            address: None,
            phone_or_fax: None,
            specialty: None,
            ncpdp_id: None,
            page_number: None,
        }
    }
}
/// Array of pharmacy specialty types to filter the search.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Specialty {
    #[serde(rename = "Any")]
    Any,
    #[serde(rename = "FaxPharmacy")]
    FaxPharmacy,
    #[serde(rename = "EPCS")]
    Epcs,
    #[serde(rename = "TwentyFourHourPharmacy")]
    TwentyFourHourPharmacy,
    #[serde(rename = "LongTermCarePharmacy")]
    LongTermCarePharmacy,
    #[serde(rename = "MailOrder")]
    MailOrder,
    #[serde(rename = "Retail")]
    Retail,
    #[serde(rename = "SpecialtyPharmacy")]
    SpecialtyPharmacy,
}

impl Default for Specialty {
    fn default() -> Specialty {
        Self::Any
    }
}

