/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrescriptionSnapshotResponse {
    #[serde(rename = "PrescriptionSnapshot", skip_serializing_if = "Option::is_none")]
    pub prescription_snapshot: Option<Box<models::PrescriptionSnapshot>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl PrescriptionSnapshotResponse {
    pub fn new() -> PrescriptionSnapshotResponse {
        PrescriptionSnapshotResponse {
            prescription_snapshot: None,
            result: None,
        }
    }
}

