/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardDispenseUnitType {
    #[serde(rename = "StandardDispenseUnitTypeID", skip_serializing_if = "Option::is_none")]
    pub standard_dispense_unit_type_id: Option<i32>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Abbreviation", skip_serializing_if = "Option::is_none")]
    pub abbreviation: Option<String>,
    #[serde(rename = "Singular", skip_serializing_if = "Option::is_none")]
    pub singular: Option<String>,
    #[serde(rename = "Plural", skip_serializing_if = "Option::is_none")]
    pub plural: Option<String>,
    #[serde(rename = "SingularOrPlural", skip_serializing_if = "Option::is_none")]
    pub singular_or_plural: Option<String>,
    #[serde(rename = "PotencyUnitCode", skip_serializing_if = "Option::is_none")]
    pub potency_unit_code: Option<String>,
    #[serde(rename = "IsActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl StandardDispenseUnitType {
    pub fn new() -> StandardDispenseUnitType {
        StandardDispenseUnitType {
            standard_dispense_unit_type_id: None,
            name: None,
            abbreviation: None,
            singular: None,
            plural: None,
            singular_or_plural: None,
            potency_unit_code: None,
            is_active: None,
        }
    }
}

