/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupervisorToClinicianRequest {
    #[serde(rename = "ClinicId")]
    pub clinic_id: crate::ids::ClinicId,
    #[serde(rename = "SupervisorId", skip_serializing_if = "Option::is_none")]
    pub supervisor_id: Option<crate::ids::ClinicianId>,
}

impl SupervisorToClinicianRequest {
    pub fn new(clinic_id: crate::ids::ClinicId) -> SupervisorToClinicianRequest {
        SupervisorToClinicianRequest {
            clinic_id,
            supervisor_id: None,
        }
    }
}

