/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproveRxChangeRequest {
    #[serde(rename = "PriorAuthNumber", skip_serializing_if = "Option::is_none")]
    pub prior_auth_number: Option<String>,
    #[serde(rename = "SelectedMedicationId", skip_serializing_if = "Option::is_none")]
    pub selected_medication_id: Option<i32>,
    #[serde(rename = "NewPrescriptionPatientId", skip_serializing_if = "Option::is_none")]
    pub new_prescription_patient_id: Option<crate::ids::PatientId>,
    #[serde(rename = "NewPrescription", skip_serializing_if = "Option::is_none")]
    pub new_prescription: Option<Box<models::CodedPrescriptionRequest>>,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "PrescriberAuthorizationData", skip_serializing_if = "Option::is_none")]
    pub prescriber_authorization_data: Option<String>,
    #[serde(rename = "PrescriberLicenseInactive", skip_serializing_if = "Option::is_none")]
    pub prescriber_license_inactive: Option<bool>,
}

impl ApproveRxChangeRequest {
    pub fn new() -> ApproveRxChangeRequest {
        ApproveRxChangeRequest {
            prior_auth_number: None,
            selected_medication_id: None,
            new_prescription_patient_id: None,
            new_prescription: None,
            comment: None,
            prescriber_authorization_data: None,
            prescriber_license_inactive: None,
        }
    }
}

