/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianSetPinRequest {
    #[serde(rename = "PIN")]
    pub pin: String,
}

impl ClinicianSetPinRequest {
    pub fn new(pin: String) -> ClinicianSetPinRequest {
        ClinicianSetPinRequest {
            pin,
        }
    }
}

