/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianAcceptAgreementRequest {
    #[serde(rename = "AgreementId")]
    pub agreement_id: i32,
    #[serde(rename = "NameSigned")]
    pub name_signed: String,
}

impl ClinicianAcceptAgreementRequest {
    pub fn new(agreement_id: i32, name_signed: String) -> ClinicianAcceptAgreementRequest {
        ClinicianAcceptAgreementRequest {
            agreement_id,
            name_signed,
        }
    }
}

