/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianIdentityProofingResponse {
    #[serde(rename = "SessionID", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(rename = "Questions", skip_serializing_if = "Option::is_none")]
    pub questions: Option<Vec<String>>,
    #[serde(rename = "Answers", skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<Vec<String>>>,
    #[serde(rename = "OtpSent", skip_serializing_if = "Option::is_none")]
    pub otp_sent: Option<bool>,
    #[serde(rename = "IdpResultSummary", skip_serializing_if = "Option::is_none")]
    pub idp_result_summary: Option<String>,
    #[serde(rename = "IDCapture", skip_serializing_if = "Option::is_none")]
    pub id_capture: Option<bool>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ClinicianIdentityProofingResponse {
    pub fn new() -> ClinicianIdentityProofingResponse {
        ClinicianIdentityProofingResponse {
            session_id: None,
            questions: None,
            answers: None,
            otp_sent: None,
            idp_result_summary: None,
            id_capture: None,
            result: None,
        }
    }
}

