/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianAddMultipleClinicsRequest {
    #[serde(rename = "ClinicIds")]
    pub clinic_ids: Vec<i32>,
}

impl ClinicianAddMultipleClinicsRequest {
    pub fn new(clinic_ids: Vec<i32>) -> ClinicianAddMultipleClinicsRequest {
        ClinicianAddMultipleClinicsRequest {
            clinic_ids,
        }
    }
}

