/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

/// ClinicianIdentityProofingOneTimeCodeRequest : represent a request to clinican identity proof one time code after success
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianIdentityProofingOneTimeCodeRequest {
    #[serde(rename = "SessionID")]
    pub session_id: String,
    /// Entered OTP
    #[serde(rename = "MobileCode")]
    pub mobile_code: String,
}

impl ClinicianIdentityProofingOneTimeCodeRequest {
    /// represent a request to clinican identity proof one time code after success
    pub fn new(session_id: String, mobile_code: String) -> ClinicianIdentityProofingOneTimeCodeRequest {
        ClinicianIdentityProofingOneTimeCodeRequest {
            session_id,
            mobile_code,
        }
    }
}

