/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianChangePinRequest {
    #[serde(rename = "CurrentPIN")]
    pub current_pin: String,
    #[serde(rename = "NewPIN")]
    pub new_pin: String,
}

impl ClinicianChangePinRequest {
    pub fn new(current_pin: String, new_pin: String) -> ClinicianChangePinRequest {
        ClinicianChangePinRequest {
            current_pin,
            new_pin,
        }
    }
}

