/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodedPrescriptionRequest {
    #[serde(rename = "DispensableDrugId")]
    pub dispensable_drug_id: crate::ids::DispensableDrugId,
    #[serde(rename = "PatientFormularyId", skip_serializing_if = "Option::is_none")]
    pub patient_formulary_id: Option<i32>,
    #[serde(rename = "FirstPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub first_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
    #[serde(rename = "SecondPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub second_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
    #[serde(rename = "InactiveDate", skip_serializing_if = "Option::is_none")]
    pub inactive_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Refills")]
    pub refills: i32,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "DispenseUnitId")]
    pub dispense_unit_id: i32,
    #[serde(rename = "Quantity")]
    pub quantity: f64,
    #[serde(rename = "Directions")]
    pub directions: String,
    #[serde(rename = "PharmacyId", skip_serializing_if = "Option::is_none")]
    pub pharmacy_id: Option<crate::ids::PharmacyId>,
    #[serde(rename = "PharmacyNotes", skip_serializing_if = "Option::is_none")]
    pub pharmacy_notes: Option<String>,
    #[serde(rename = "NoSubstitutions", skip_serializing_if = "Option::is_none")]
    pub no_substitutions: Option<bool>,
    #[serde(rename = "EffectiveDate", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "RxReferenceNumber", skip_serializing_if = "Option::is_none")]
    pub rx_reference_number: Option<String>,
    #[serde(rename = "EligibilityId", skip_serializing_if = "Option::is_none")]
    pub eligibility_id: Option<crate::ids::EligibilityId>,
    #[serde(rename = "NonDoseSpotPrescriptionId", skip_serializing_if = "Option::is_none")]
    pub non_dose_spot_prescription_id: Option<String>,
    #[serde(rename = "IsRefillReplace", skip_serializing_if = "Option::is_none")]
    pub is_refill_replace: Option<bool>,
    #[serde(rename = "IsUrgent", skip_serializing_if = "Option::is_none")]
    pub is_urgent: Option<bool>,
    #[serde(rename = "SupervisorId", skip_serializing_if = "Option::is_none")]
    pub supervisor_id: Option<crate::ids::ClinicianId>,
    #[serde(rename = "RetailPharmacyToMailToPatient", skip_serializing_if = "Option::is_none")]
    pub retail_pharmacy_to_mail_to_patient: Option<bool>,
    #[serde(rename = "Status")]
    pub status: Status,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "Encounter", skip_serializing_if = "Option::is_none")]
    pub encounter: Option<String>,
}

impl CodedPrescriptionRequest {
    pub fn new(dispensable_drug_id: crate::ids::DispensableDrugId, refills: i32, dispense_unit_id: i32, quantity: f64, directions: String, status: Status) -> CodedPrescriptionRequest {
        CodedPrescriptionRequest {
            dispensable_drug_id,
            patient_formulary_id: None,
            first_prescription_diagnosis: None,
            second_prescription_diagnosis: None,
            inactive_date: None,
            refills,
            days_supply: None,
            dispense_unit_id,
            quantity,
            directions,
            pharmacy_id: None,
            pharmacy_notes: None,
            no_substitutions: None,
            effective_date: None,
            rx_reference_number: None,
            eligibility_id: None,
            non_dose_spot_prescription_id: None,
            is_refill_replace: None,
            is_urgent: None,
            supervisor_id: None,
            retail_pharmacy_to_mail_to_patient: None,
            status,
            comment: None,
            encounter: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Discontinued")]
    Discontinued,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "CancelPending")]
    CancelPending,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Changed")]
    Changed,
    #[serde(rename = "FullFill")]
    FullFill,
    #[serde(rename = "PartialFill")]
    PartialFill,
    #[serde(rename = "NoFill")]
    NoFill,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}

