/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Diagnosis {
    #[serde(rename = "DiagnosisId", skip_serializing_if = "Option::is_none")]
    pub diagnosis_id: Option<crate::ids::DiagnosisId>,
    #[serde(rename = "DiagnosisCode", skip_serializing_if = "Option::is_none")]
    pub diagnosis_code: Option<String>,
    #[serde(rename = "DiagnosisDescription", skip_serializing_if = "Option::is_none")]
    pub diagnosis_description: Option<String>,
}

impl Diagnosis {
    pub fn new() -> Diagnosis {
        Diagnosis {
            diagnosis_id: None,
            diagnosis_code: None,
            diagnosis_description: None,
        }
    }
}

