/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRefillRequest {
    #[serde(rename = "Clinic", skip_serializing_if = "Option::is_none")]
    pub clinic: Option<Clinic>,
    #[serde(rename = "PatientId", skip_serializing_if = "Option::is_none")]
    pub patient_id: Option<crate::ids::PatientId>,
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
}

impl GetRefillRequest {
    pub fn new() -> GetRefillRequest {
        GetRefillRequest {
            clinic: None,
            patient_id: None,
            page_number: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Clinic {
    #[serde(rename = "All")]
    All,
    #[serde(rename = "Current")]
    Current,
}

impl Default for Clinic {
    fn default() -> Clinic {
        Self::All
    }
}

