/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPharmacyRestrictionsRequest {
    #[serde(rename = "DispensableDrugId")]
    pub dispensable_drug_id: crate::ids::DispensableDrugId,
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
}

impl GetPharmacyRestrictionsRequest {
    pub fn new(dispensable_drug_id: crate::ids::DispensableDrugId) -> GetPharmacyRestrictionsRequest {
        GetPharmacyRestrictionsRequest {
            dispensable_drug_id,
            page_number: None,
        }
    }
}

