/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrescriptionBenefitResponse {
    #[serde(rename = "PatientFormularyId", skip_serializing_if = "Option::is_none")]
    pub patient_formulary_id: Option<i32>,
    #[serde(rename = "Brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<bool>,
    #[serde(rename = "Otc", skip_serializing_if = "Option::is_none")]
    pub otc: Option<bool>,
    #[serde(rename = "Alternatives", skip_serializing_if = "Option::is_none")]
    pub alternatives: Option<Vec<models::PayerAlternativeApi>>,
    #[serde(rename = "RealTimeFormularyRequestStatus", skip_serializing_if = "Option::is_none")]
    pub real_time_formulary_request_status: Option<i32>,
    #[serde(rename = "PatientSpecificPricingCoverages", skip_serializing_if = "Option::is_none")]
    pub patient_specific_pricing_coverages: Option<Vec<models::PatientSpecificPricingCoverage>>,
    #[serde(rename = "OptionalPharmacy", skip_serializing_if = "Option::is_none")]
    pub optional_pharmacy: Option<Box<models::PrescriptionBenefitsPharmacy>>,
}

impl GetPrescriptionBenefitResponse {
    pub fn new() -> GetPrescriptionBenefitResponse {
        GetPrescriptionBenefitResponse {
            patient_formulary_id: None,
            brand: None,
            otc: None,
            alternatives: None,
            real_time_formulary_request_status: None,
            patient_specific_pricing_coverages: None,
            optional_pharmacy: None,
        }
    }
}

