/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

/// ItemResponsePdmpResponse : Represents a generic response containing a single object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemResponsePdmpResponse {
    #[serde(rename = "Item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::PdmpResponse>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ItemResponsePdmpResponse {
    /// Represents a generic response containing a single object.
    pub fn new() -> ItemResponsePdmpResponse {
        ItemResponsePdmpResponse {
            item: None,
            result: None,
        }
    }
}

