/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

/// ListResponseClinician : Represents a generic response containing a list of objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponseClinician {
    /// The list of elements to return.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::Clinician>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ListResponseClinician {
    /// Represents a generic response containing a list of objects.
    pub fn new() -> ListResponseClinician {
        ListResponseClinician {
            items: None,
            result: None,
        }
    }
}

