/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderSetDetailsResponse {
    #[serde(rename = "OrderSetId", skip_serializing_if = "Option::is_none")]
    pub order_set_id: Option<crate::ids::OrderSetId>,
    #[serde(rename = "Title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "Favorites", skip_serializing_if = "Option::is_none")]
    pub favorites: Option<Vec<models::ClinicianFavoritePrescriptionResponse>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl OrderSetDetailsResponse {
    pub fn new() -> OrderSetDetailsResponse {
        OrderSetDetailsResponse {
            order_set_id: None,
            title: None,
            favorites: None,
            result: None,
        }
    }
}

