/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaAnswers {
    #[serde(rename = "Answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    #[serde(rename = "AnswerDateTime", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub answer_date_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "AnswerNumeric", skip_serializing_if = "Option::is_none")]
    pub answer_numeric: Option<f64>,
    #[serde(rename = "AnswerFreeText", skip_serializing_if = "Option::is_none")]
    pub answer_free_text: Option<String>,
}

impl PaAnswers {
    pub fn new() -> PaAnswers {
        PaAnswers {
            answer: None,
            answer_date_time: None,
            answer_numeric: None,
            answer_free_text: None,
        }
    }
}

