/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatientSsnRequestModel {
    #[serde(rename = "PatientSSN")]
    pub patient_ssn: String,
}

impl PatientSsnRequestModel {
    pub fn new(patient_ssn: String) -> PatientSsnRequestModel {
        PatientSsnRequestModel {
            patient_ssn,
        }
    }
}

