/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayerCopay {
    #[serde(rename = "IsDrugSpecific", skip_serializing_if = "Option::is_none")]
    pub is_drug_specific: Option<bool>,
    #[serde(rename = "PharmacyType", skip_serializing_if = "Option::is_none")]
    pub pharmacy_type: Option<PharmacyType>,
    #[serde(rename = "FlatCopayAmount", skip_serializing_if = "Option::is_none")]
    pub flat_copay_amount: Option<f64>,
    #[serde(rename = "PercentCopayAmount", skip_serializing_if = "Option::is_none")]
    pub percent_copay_amount: Option<f64>,
    #[serde(rename = "FlatCopayAmountFirst", skip_serializing_if = "Option::is_none")]
    pub flat_copay_amount_first: Option<bool>,
    #[serde(rename = "MinimumCopayAmount", skip_serializing_if = "Option::is_none")]
    pub minimum_copay_amount: Option<f64>,
    #[serde(rename = "MaximumCopayAmount", skip_serializing_if = "Option::is_none")]
    pub maximum_copay_amount: Option<f64>,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "CopayTier", skip_serializing_if = "Option::is_none")]
    pub copay_tier: Option<i32>,
    #[serde(rename = "MaximumCopayTier", skip_serializing_if = "Option::is_none")]
    pub maximum_copay_tier: Option<i32>,
    #[serde(rename = "OutOfPocketMinimum", skip_serializing_if = "Option::is_none")]
    pub out_of_pocket_minimum: Option<f64>,
    #[serde(rename = "OutOfPocketMaximum", skip_serializing_if = "Option::is_none")]
    pub out_of_pocket_maximum: Option<f64>,
}

impl PayerCopay {
    pub fn new() -> PayerCopay {
        PayerCopay {
            is_drug_specific: None,
            pharmacy_type: None,
            flat_copay_amount: None,
            percent_copay_amount: None,
            flat_copay_amount_first: None,
            minimum_copay_amount: None,
            maximum_copay_amount: None,
            days_supply: None,
            copay_tier: None,
            maximum_copay_tier: None,
            out_of_pocket_minimum: None,
            out_of_pocket_maximum: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PharmacyType {
    #[serde(rename = "Any")]
    Any,
    #[serde(rename = "FaxPharmacy")]
    FaxPharmacy,
    #[serde(rename = "EPCS")]
    Epcs,
    #[serde(rename = "TwentyFourHourPharmacy")]
    TwentyFourHourPharmacy,
    #[serde(rename = "LongTermCarePharmacy")]
    LongTermCarePharmacy,
    #[serde(rename = "MailOrder")]
    MailOrder,
    #[serde(rename = "Retail")]
    Retail,
    #[serde(rename = "SpecialtyPharmacy")]
    SpecialtyPharmacy,
}

impl Default for PharmacyType {
    fn default() -> PharmacyType {
        Self::Any
    }
}

