/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayerInformationResponse {
    #[serde(rename = "PatientEligibilityId", skip_serializing_if = "Option::is_none")]
    pub patient_eligibility_id: Option<i32>,
    #[serde(rename = "PayerName", skip_serializing_if = "Option::is_none")]
    pub payer_name: Option<String>,
    #[serde(rename = "PharmacyEligibilities", skip_serializing_if = "Option::is_none")]
    pub pharmacy_eligibilities: Option<Vec<models::PharmacyEligibility>>,
    #[serde(rename = "PlanName", skip_serializing_if = "Option::is_none")]
    pub plan_name: Option<String>,
    #[serde(rename = "CoverageId", skip_serializing_if = "Option::is_none")]
    pub coverage_id: Option<String>,
    #[serde(rename = "PayerId", skip_serializing_if = "Option::is_none")]
    pub payer_id: Option<String>,
    #[serde(rename = "BIN", skip_serializing_if = "Option::is_none")]
    pub bin: Option<String>,
    #[serde(rename = "PCN", skip_serializing_if = "Option::is_none")]
    pub pcn: Option<String>,
    #[serde(rename = "FormularyId", skip_serializing_if = "Option::is_none")]
    pub formulary_id: Option<String>,
    #[serde(rename = "AlternativesId", skip_serializing_if = "Option::is_none")]
    pub alternatives_id: Option<String>,
    #[serde(rename = "CopayId", skip_serializing_if = "Option::is_none")]
    pub copay_id: Option<String>,
    #[serde(rename = "DemographicChanges", skip_serializing_if = "Option::is_none")]
    pub demographic_changes: Option<bool>,
    #[serde(rename = "Demographics", skip_serializing_if = "Option::is_none")]
    pub demographics: Option<Box<models::PayerDemographics>>,
    #[serde(rename = "ErrorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "InfoMessage", skip_serializing_if = "Option::is_none")]
    pub info_message: Option<String>,
    #[serde(rename = "MemberId", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
}

impl PayerInformationResponse {
    pub fn new() -> PayerInformationResponse {
        PayerInformationResponse {
            patient_eligibility_id: None,
            payer_name: None,
            pharmacy_eligibilities: None,
            plan_name: None,
            coverage_id: None,
            payer_id: None,
            bin: None,
            pcn: None,
            formulary_id: None,
            alternatives_id: None,
            copay_id: None,
            demographic_changes: None,
            demographics: None,
            error_message: None,
            info_message: None,
            member_id: None,
        }
    }
}

