/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayerAlternative {
    #[serde(rename = "Ndc", skip_serializing_if = "Option::is_none")]
    pub ndc: Option<String>,
    #[serde(rename = "Details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<models::PayerAlternativeDetail>>,
}

impl PayerAlternative {
    pub fn new() -> PayerAlternative {
        PayerAlternative {
            ndc: None,
            details: None,
        }
    }
}

