/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

/// PharmacyAlternativeRequest : Represents a request to add a pharmacy alternative.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PharmacyAlternativeRequest {
    /// The NDC of the medication.
    #[serde(rename = "NDC")]
    pub ndc: String,
}

impl PharmacyAlternativeRequest {
    /// Represents a request to add a pharmacy alternative.
    pub fn new(ndc: String) -> PharmacyAlternativeRequest {
        PharmacyAlternativeRequest {
            ndc,
        }
    }
}

