/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrescriptionSnapshot {
    #[serde(rename = "Prescriber", skip_serializing_if = "Option::is_none")]
    pub prescriber: Option<Box<models::PrescriberSnapshot>>,
    #[serde(rename = "Patient", skip_serializing_if = "Option::is_none")]
    pub patient: Option<Box<models::PatientSnapshot>>,
    #[serde(rename = "Agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::AgentSnapshot>>,
    #[serde(rename = "Supervisor", skip_serializing_if = "Option::is_none")]
    pub supervisor: Option<Box<models::SupervisorSnapshot>>,
    #[serde(rename = "Pharmacy", skip_serializing_if = "Option::is_none")]
    pub pharmacy: Option<Box<models::PharmacySnapshot>>,
    #[serde(rename = "Medication", skip_serializing_if = "Option::is_none")]
    pub medication: Option<Box<models::MedicationSnapshot>>,
}

impl PrescriptionSnapshot {
    pub fn new() -> PrescriptionSnapshot {
        PrescriptionSnapshot {
            prescriber: None,
            patient: None,
            agent: None,
            supervisor: None,
            pharmacy: None,
            medication: None,
        }
    }
}

