/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthorizationQuestionResponseChoice {
    #[serde(rename = "QuestionChoiceId", skip_serializing_if = "Option::is_none")]
    pub question_choice_id: Option<i32>,
    #[serde(rename = "QuestionChoiceText", skip_serializing_if = "Option::is_none")]
    pub question_choice_text: Option<String>,
    #[serde(rename = "AdditionalFreeTextRequired", skip_serializing_if = "Option::is_none")]
    pub additional_free_text_required: Option<bool>,
    #[serde(rename = "AdditionalFreeTextAllowed", skip_serializing_if = "Option::is_none")]
    pub additional_free_text_allowed: Option<bool>,
}

impl PriorAuthorizationQuestionResponseChoice {
    pub fn new() -> PriorAuthorizationQuestionResponseChoice {
        PriorAuthorizationQuestionResponseChoice {
            question_choice_id: None,
            question_choice_text: None,
            additional_free_text_required: None,
            additional_free_text_allowed: None,
        }
    }
}

