/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthorizationHistoryResponse {
    #[serde(rename = "FinalStatus", skip_serializing_if = "Option::is_none")]
    pub final_status: Option<String>,
    #[serde(rename = "AuthorizationNumber", skip_serializing_if = "Option::is_none")]
    pub authorization_number: Option<String>,
    #[serde(rename = "EffectiveDate", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub effective_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ExpirationDate", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub expiration_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "CanAppeal", skip_serializing_if = "Option::is_none")]
    pub can_appeal: Option<String>,
    #[serde(rename = "IsOffline", skip_serializing_if = "Option::is_none")]
    pub is_offline: Option<bool>,
    #[serde(rename = "Attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::PaAttachment>>,
    #[serde(rename = "StatusLogs", skip_serializing_if = "Option::is_none")]
    pub status_logs: Option<Vec<models::PaStatusLog>>,
    #[serde(rename = "QuestionSets", skip_serializing_if = "Option::is_none")]
    pub question_sets: Option<Vec<models::PaHistoryQuestionSet>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl PriorAuthorizationHistoryResponse {
    pub fn new() -> PriorAuthorizationHistoryResponse {
        PriorAuthorizationHistoryResponse {
            final_status: None,
            authorization_number: None,
            effective_date: None,
            expiration_date: None,
            note: None,
            can_appeal: None,
            is_offline: None,
            attachments: None,
            status_logs: None,
            question_sets: None,
            result: None,
        }
    }
}

