/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthApproveOfflineRequest {
    #[serde(rename = "AuthorizationNumber")]
    pub authorization_number: String,
}

impl PriorAuthApproveOfflineRequest {
    pub fn new(authorization_number: String) -> PriorAuthApproveOfflineRequest {
        PriorAuthApproveOfflineRequest {
            authorization_number,
        }
    }
}

