/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthorizationChoiceAnswer {
    #[serde(rename = "PriorAuthorizationQuestionChoiceId", skip_serializing_if = "Option::is_none")]
    pub prior_authorization_question_choice_id: Option<i32>,
    #[serde(rename = "PriorAuthorizationQuestionChoiceText", skip_serializing_if = "Option::is_none")]
    pub prior_authorization_question_choice_text: Option<String>,
}

impl PriorAuthorizationChoiceAnswer {
    pub fn new() -> PriorAuthorizationChoiceAnswer {
        PriorAuthorizationChoiceAnswer {
            prior_authorization_question_choice_id: None,
            prior_authorization_question_choice_text: None,
        }
    }
}

