/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceRefillRequest {
    #[serde(rename = "PatientID")]
    pub patient_id: crate::ids::PatientId,
    #[serde(rename = "Pin", skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    #[serde(rename = "Otp", skip_serializing_if = "Option::is_none")]
    pub otp: Option<String>,
    #[serde(rename = "NewPrescription", skip_serializing_if = "Option::is_none")]
    pub new_prescription: Option<Box<models::CodedPrescriptionRequestUi>>,
    #[serde(rename = "NewSupplyPrescription", skip_serializing_if = "Option::is_none")]
    pub new_supply_prescription: Option<Box<models::CodedSupplyRequest>>,
    #[serde(rename = "NewCompoundPrescription", skip_serializing_if = "Option::is_none")]
    pub new_compound_prescription: Option<Box<models::CompoundPrescriptionRequestUi>>,
    #[serde(rename = "NewFreeTextPrescription", skip_serializing_if = "Option::is_none")]
    pub new_free_text_prescription: Option<Box<models::FreeTextPrescriptionRequest>>,
}

impl ReplaceRefillRequest {
    pub fn new(patient_id: crate::ids::PatientId) -> ReplaceRefillRequest {
        ReplaceRefillRequest {
            patient_id,
            pin: None,
            otp: None,
            new_prescription: None,
            new_supply_prescription: None,
            new_compound_prescription: None,
            new_free_text_prescription: None,
        }
    }
}

