/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendPrescriptionsRequest {
    #[serde(rename = "Pin", skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    #[serde(rename = "PrescriptionIds")]
    pub prescription_ids: Vec<i32>,
    #[serde(rename = "PharmacyOverride", skip_serializing_if = "Option::is_none")]
    pub pharmacy_override: Option<bool>,
}

impl SendPrescriptionsRequest {
    pub fn new(prescription_ids: Vec<i32>) -> SendPrescriptionsRequest {
        SendPrescriptionsRequest {
            pin: None,
            prescription_ids,
            pharmacy_override: None,
        }
    }
}

