/*
 * DoseSpot REST API - Plan: Full - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: FullV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateSchedule {
    #[serde(rename = "StateName", skip_serializing_if = "Option::is_none")]
    pub state_name: Option<String>,
    #[serde(rename = "Schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<i32>,
}

impl StateSchedule {
    pub fn new() -> StateSchedule {
        StateSchedule {
            state_name: None,
            schedule: None,
        }
    }
}

