/*
 * DoseSpot REST API - Plan: Jumpstart - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpstartV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::jumpstart::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`allergies_add_coded_patient_allergy_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllergiesAddCodedPatientAllergyV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`allergies_add_freetext_patient_allergy_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllergiesAddFreetextPatientAllergyV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`allergies_add_no_known_patient_allergy_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllergiesAddNoKnownPatientAllergyV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`allergies_edit_patient_allergy_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllergiesEditPatientAllergyV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`allergies_get_patient_allergies_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllergiesGetPatientAllergiesV2Error {
    UnknownValue(serde_json::Value),
}


/// Adds an coded allergy to a patient record
pub async fn allergies_add_coded_patient_allergy_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, request: models::CodedPatientAllergyRequest) -> Result<models::IdentifierResponse, Error<AllergiesAddCodedPatientAllergyV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/allergies/coded", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AllergiesAddCodedPatientAllergyV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Adds an freetext allergy to a patient record
pub async fn allergies_add_freetext_patient_allergy_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, request: models::FreetextPatientAllergyRequest) -> Result<models::IdentifierResponse, Error<AllergiesAddFreetextPatientAllergyV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/allergies/freetext", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AllergiesAddFreetextPatientAllergyV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Adds an no known patient allergy record
pub async fn allergies_add_no_known_patient_allergy_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::IdentifierResponse, Error<AllergiesAddNoKnownPatientAllergyV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/allergies/noKnownAllergy", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AllergiesAddNoKnownPatientAllergyV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing drug allergy in a patient
pub async fn allergies_edit_patient_allergy_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId, patient_allergy_id: crate::ids::PatientAllergyId, request: models::EditPatientAllergyRequest) -> Result<models::Response, Error<AllergiesEditPatientAllergyV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;
    let p_path_patient_allergy_id = patient_allergy_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/patients/{patientId}/allergies/{patientAllergyId}", configuration.base_path, patientId=p_path_patient_id, patientAllergyId=p_path_patient_allergy_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AllergiesEditPatientAllergyV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves a detailed list of all allergies for a given patient
pub async fn allergies_get_patient_allergies_v2(configuration: &configuration::Configuration, patient_id: crate::ids::PatientId) -> Result<models::ListResponsePatientAllergy, Error<AllergiesGetPatientAllergiesV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_patient_id = patient_id;

    let uri_str = format!("{}/api/patients/{patientId}/allergies", configuration.base_path, patientId=p_path_patient_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListResponsePatientAllergy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListResponsePatientAllergy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AllergiesGetPatientAllergiesV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

