/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::full_epcs::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clinic_groups_add_edit_clinic_group_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClinicGroupsAddEditClinicGroupV2Error {
    UnknownValue(serde_json::Value),
}


/// Handles clinic group actions which include adding and modifying clinic list in a clinic group.
pub async fn clinic_groups_add_edit_clinic_group_v2(configuration: &configuration::Configuration, request: models::AddEditClinicGroupRequest) -> Result<Vec<models::AddEditClinicGroupResponse>, Error<ClinicGroupsAddEditClinicGroupV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request = request;

    let uri_str = format!("{}/api/clinicGroups", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AddEditClinicGroupResponse&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::AddEditClinicGroupResponse&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClinicGroupsAddEditClinicGroupV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

