/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::full_epcs::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`refills_approve_refill_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsApproveRefillV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refills_change_refill_request_patient_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsChangeRefillRequestPatientV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refills_deny_refill_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsDenyRefillV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refills_get_detailed_refill_requests_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsGetDetailedRefillRequestsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refills_get_refill_request_details_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsGetRefillRequestDetailsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refills_replace_refill_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefillsReplaceRefillV2Error {
    UnknownValue(serde_json::Value),
}


/// Approves a pending refill request by providing the number of refills
pub async fn refills_approve_refill_v2(configuration: &configuration::Configuration, refill_id: crate::ids::RefillId, request: models::ApproveRefillRequest) -> Result<models::IdentifierResponse, Error<RefillsApproveRefillV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_refill_id = refill_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/refills/{refillId}/approve", configuration.base_path, refillId=p_path_refill_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsApproveRefillV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Provides the ability to link a refill request to a different, existing patient in the same clinic.  This is only applicable for refill requests that came in from the pharmacy with discrepancies in a patient’s name,  date of birth, or gender and were not able to be automatically linked to the appropriate, existing patient within DoseSpot.
pub async fn refills_change_refill_request_patient_v2(configuration: &configuration::Configuration, refill_id: crate::ids::RefillId, request: models::ChangeRefillPatientRequest) -> Result<models::Response, Error<RefillsChangeRefillRequestPatientV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_refill_id = refill_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/refills/{refillId}/changePatient", configuration.base_path, refillId=p_path_refill_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsChangeRefillRequestPatientV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Denies a pending refill request by providing the denial reason
pub async fn refills_deny_refill_v2(configuration: &configuration::Configuration, refill_id: crate::ids::RefillId, request: models::DenyRefillRequest) -> Result<models::IdentifierResponse, Error<RefillsDenyRefillV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_refill_id = refill_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/refills/{refillId}/deny", configuration.base_path, refillId=p_path_refill_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsDenyRefillV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information on refill requests associated with clinician's clinic(s)/patient
pub async fn refills_get_detailed_refill_requests_v2(configuration: &configuration::Configuration, clinic: Option<&str>, patient_id: Option<crate::ids::PatientId>, page_number: Option<i32>) -> Result<models::PagedListResponseGetRefillDetailedResponse, Error<RefillsGetDetailedRefillRequestsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_clinic = clinic;
    let p_query_patient_id = patient_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/refills/pending/detailed", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_clinic {
        req_builder = req_builder.query(&[("clinic", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_patient_id {
        req_builder = req_builder.query(&[("patientId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseGetRefillDetailedResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseGetRefillDetailedResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsGetDetailedRefillRequestsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves information on refill requests associated with clinician's clinic(s)/patient
pub async fn refills_get_refill_request_details_v2(configuration: &configuration::Configuration, clinic: Option<&str>, patient_id: Option<crate::ids::PatientId>, page_number: Option<i32>) -> Result<models::PagedListResponseGetRefillResponse, Error<RefillsGetRefillRequestDetailsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_clinic = clinic;
    let p_query_patient_id = patient_id;
    let p_query_page_number = page_number;

    let uri_str = format!("{}/api/refills/pending", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_clinic {
        req_builder = req_builder.query(&[("clinic", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_patient_id {
        req_builder = req_builder.query(&[("patientId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_number {
        req_builder = req_builder.query(&[("pageNumber", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedListResponseGetRefillResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedListResponseGetRefillResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsGetRefillRequestDetailsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Provides the ability to replace a refill request with a different medication.
pub async fn refills_replace_refill_v2(configuration: &configuration::Configuration, refill_id: crate::ids::RefillId, request: models::ReplaceRefillRequest) -> Result<models::IdentifierResponse, Error<RefillsReplaceRefillV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_refill_id = refill_id;
    let p_body_request = request;

    let uri_str = format!("{}/api/refills/{refillId}/replace", configuration.base_path, refillId=p_path_refill_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefillsReplaceRefillV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

