/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddEditClinicGroupResponse {
    #[serde(rename = "UserId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "ClientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<i32>,
    #[serde(rename = "ClientName", skip_serializing_if = "Option::is_none")]
    pub client_name: Option<String>,
    #[serde(rename = "ClinicIds", skip_serializing_if = "Option::is_none")]
    pub clinic_ids: Option<Vec<i32>>,
    #[serde(rename = "ClinicGroupName", skip_serializing_if = "Option::is_none")]
    pub clinic_group_name: Option<String>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl AddEditClinicGroupResponse {
    pub fn new() -> AddEditClinicGroupResponse {
        AddEditClinicGroupResponse {
            user_id: None,
            client_id: None,
            client_name: None,
            clinic_ids: None,
            clinic_group_name: None,
            result: None,
        }
    }
}

