/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgreementInfoResponse {
    #[serde(rename = "AgreementId", skip_serializing_if = "Option::is_none")]
    pub agreement_id: Option<i32>,
    #[serde(rename = "AgreementDate", skip_serializing_if = "Option::is_none")]
    pub agreement_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "AgreementText", skip_serializing_if = "Option::is_none")]
    pub agreement_text: Option<String>,
}

impl AgreementInfoResponse {
    pub fn new() -> AgreementInfoResponse {
        AgreementInfoResponse {
            agreement_id: None,
            agreement_date: None,
            agreement_text: None,
        }
    }
}

