/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRefillPatientRequest {
    #[serde(rename = "PatientId")]
    pub patient_id: crate::ids::PatientId,
}

impl ChangeRefillPatientRequest {
    pub fn new(patient_id: crate::ids::PatientId) -> ChangeRefillPatientRequest {
        ChangeRefillPatientRequest {
            patient_id,
        }
    }
}

