/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianClinicsRequest {
    #[serde(rename = "IncludeClinicGroups", skip_serializing_if = "Option::is_none")]
    pub include_clinic_groups: Option<bool>,
    #[serde(rename = "ClinicStatus", skip_serializing_if = "Option::is_none")]
    pub clinic_status: Option<ClinicStatus>,
}

impl ClinicianClinicsRequest {
    pub fn new() -> ClinicianClinicsRequest {
        ClinicianClinicsRequest {
            include_clinic_groups: None,
            clinic_status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClinicStatus {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "All")]
    All,
}

impl Default for ClinicStatus {
    fn default() -> ClinicStatus {
        Self::Active
    }
}

