/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeaNumberResponse {
    #[serde(rename = "DEANumberId", skip_serializing_if = "Option::is_none")]
    pub dea_number_id: Option<uuid::Uuid>,
    #[serde(rename = "DEANumber", skip_serializing_if = "Option::is_none")]
    pub dea_number: Option<String>,
    #[serde(rename = "AddressLine1", skip_serializing_if = "Option::is_none")]
    pub address_line1: Option<String>,
    #[serde(rename = "AddressLine2", skip_serializing_if = "Option::is_none")]
    pub address_line2: Option<String>,
    #[serde(rename = "City", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "State", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "Zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
}

impl DeaNumberResponse {
    pub fn new() -> DeaNumberResponse {
        DeaNumberResponse {
            dea_number_id: None,
            dea_number: None,
            address_line1: None,
            address_line2: None,
            city: None,
            state: None,
            zip: None,
        }
    }
}

