/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormularyInfo {
    #[serde(rename = "ProductId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<i32>,
    #[serde(rename = "Ndc", skip_serializing_if = "Option::is_none")]
    pub ndc: Option<String>,
    #[serde(rename = "FormularyStatusId", skip_serializing_if = "Option::is_none")]
    pub formulary_status_id: Option<i32>,
    #[serde(rename = "FormularyAbbreviation", skip_serializing_if = "Option::is_none")]
    pub formulary_abbreviation: Option<String>,
    #[serde(rename = "FormularyStatusMessage", skip_serializing_if = "Option::is_none")]
    pub formulary_status_message: Option<String>,
    #[serde(rename = "OrderRank", skip_serializing_if = "Option::is_none")]
    pub order_rank: Option<i32>,
    #[serde(rename = "IsGeneric", skip_serializing_if = "Option::is_none")]
    pub is_generic: Option<bool>,
    #[serde(rename = "IsRx", skip_serializing_if = "Option::is_none")]
    pub is_rx: Option<bool>,
}

impl FormularyInfo {
    pub fn new() -> FormularyInfo {
        FormularyInfo {
            product_id: None,
            ndc: None,
            formulary_status_id: None,
            formulary_abbreviation: None,
            formulary_status_message: None,
            order_rank: None,
            is_generic: None,
            is_rx: None,
        }
    }
}

