/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRxChangeResponse {
    #[serde(rename = "RxChangeRequestId", skip_serializing_if = "Option::is_none")]
    pub rx_change_request_id: Option<i32>,
    #[serde(rename = "RxChangeType", skip_serializing_if = "Option::is_none")]
    pub rx_change_type: Option<String>,
    #[serde(rename = "RxChangeSubType", skip_serializing_if = "Option::is_none")]
    pub rx_change_sub_type: Option<String>,
    #[serde(rename = "Source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "NewPatient", skip_serializing_if = "Option::is_none")]
    pub new_patient: Option<bool>,
    #[serde(rename = "Patient", skip_serializing_if = "Option::is_none")]
    pub patient: Option<Box<models::Patient>>,
    #[serde(rename = "UnmatchedChange", skip_serializing_if = "Option::is_none")]
    pub unmatched_change: Option<bool>,
    #[serde(rename = "PrescribedPrescriptionId", skip_serializing_if = "Option::is_none")]
    pub prescribed_prescription_id: Option<i32>,
    #[serde(rename = "RequestedMedications", skip_serializing_if = "Option::is_none")]
    pub requested_medications: Option<Vec<i32>>,
    #[serde(rename = "ClinicianId", skip_serializing_if = "Option::is_none")]
    pub clinician_id: Option<crate::ids::ClinicianId>,
    #[serde(rename = "ClinicId", skip_serializing_if = "Option::is_none")]
    pub clinic_id: Option<crate::ids::ClinicId>,
    #[serde(rename = "PharmacyId", skip_serializing_if = "Option::is_none")]
    pub pharmacy_id: Option<crate::ids::PharmacyId>,
    #[serde(rename = "RequestedDate", skip_serializing_if = "Option::is_none")]
    pub requested_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "RequestExpirationDate", skip_serializing_if = "Option::is_none")]
    pub request_expiration_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "OriginalPrescriptionId", skip_serializing_if = "Option::is_none")]
    pub original_prescription_id: Option<crate::ids::PrescriptionId>,
    #[serde(rename = "PayerName", skip_serializing_if = "Option::is_none")]
    pub payer_name: Option<String>,
    #[serde(rename = "DrugUseEvaluations", skip_serializing_if = "Option::is_none")]
    pub drug_use_evaluations: Option<Vec<models::DrugUseEvaluation>>,
}

impl GetRxChangeResponse {
    pub fn new() -> GetRxChangeResponse {
        GetRxChangeResponse {
            rx_change_request_id: None,
            rx_change_type: None,
            rx_change_sub_type: None,
            source: None,
            new_patient: None,
            patient: None,
            unmatched_change: None,
            prescribed_prescription_id: None,
            requested_medications: None,
            clinician_id: None,
            clinic_id: None,
            pharmacy_id: None,
            requested_date: None,
            request_expiration_date: None,
            original_prescription_id: None,
            payer_name: None,
            drug_use_evaluations: None,
        }
    }
}

