/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRefillDetailedResponse {
    #[serde(rename = "RefillId", skip_serializing_if = "Option::is_none")]
    pub refill_id: Option<crate::ids::RefillId>,
    #[serde(rename = "NewPatient", skip_serializing_if = "Option::is_none")]
    pub new_patient: Option<bool>,
    #[serde(rename = "Patient", skip_serializing_if = "Option::is_none")]
    pub patient: Option<Box<models::Patient>>,
    #[serde(rename = "ClinicId", skip_serializing_if = "Option::is_none")]
    pub clinic_id: Option<crate::ids::ClinicId>,
    #[serde(rename = "ClinicianId", skip_serializing_if = "Option::is_none")]
    pub clinician_id: Option<crate::ids::ClinicianId>,
    #[serde(rename = "RequestedPrescription", skip_serializing_if = "Option::is_none")]
    pub requested_prescription: Option<Box<models::Prescription>>,
    #[serde(rename = "DispensedPrescription", skip_serializing_if = "Option::is_none")]
    pub dispensed_prescription: Option<Box<models::Prescription>>,
    #[serde(rename = "OriginalPrescription", skip_serializing_if = "Option::is_none")]
    pub original_prescription: Option<Box<models::Prescription>>,
    #[serde(rename = "PharmacyId", skip_serializing_if = "Option::is_none")]
    pub pharmacy_id: Option<crate::ids::PharmacyId>,
    #[serde(rename = "RequestedDate", skip_serializing_if = "Option::is_none")]
    pub requested_date: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetRefillDetailedResponse {
    pub fn new() -> GetRefillDetailedResponse {
        GetRefillDetailedResponse {
            refill_id: None,
            new_patient: None,
            patient: None,
            clinic_id: None,
            clinician_id: None,
            requested_prescription: None,
            dispensed_prescription: None,
            original_prescription: None,
            pharmacy_id: None,
            requested_date: None,
        }
    }
}

