/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

/// ItemResponseGetPatient : Represents a generic response containing a single object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemResponseGetPatient {
    #[serde(rename = "Item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::GetPatient>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ItemResponseGetPatient {
    /// Represents a generic response containing a single object.
    pub fn new() -> ItemResponseGetPatient {
        ItemResponseGetPatient {
            item: None,
            result: None,
        }
    }
}

