/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaFinalStatus {
    #[serde(rename = "PriorAuthorizationStatusType", skip_serializing_if = "Option::is_none")]
    pub prior_authorization_status_type: Option<PriorAuthorizationStatusType>,
    #[serde(rename = "ClosedReasonCodeId", skip_serializing_if = "Option::is_none")]
    pub closed_reason_code_id: Option<ClosedReasonCodeId>,
    #[serde(rename = "AuthorizationNumber", skip_serializing_if = "Option::is_none")]
    pub authorization_number: Option<String>,
    #[serde(rename = "AuthorizationPeriodStart", skip_serializing_if = "Option::is_none")]
    pub authorization_period_start: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "AuthorizationPeriodEnd", skip_serializing_if = "Option::is_none")]
    pub authorization_period_end: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "PharmacyType", skip_serializing_if = "Option::is_none")]
    pub pharmacy_type: Option<PharmacyType>,
    #[serde(rename = "Quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<String>,
    #[serde(rename = "NumberOfCycles", skip_serializing_if = "Option::is_none")]
    pub number_of_cycles: Option<String>,
    #[serde(rename = "NumberOfRefills", skip_serializing_if = "Option::is_none")]
    pub number_of_refills: Option<String>,
    #[serde(rename = "Note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "CanAppeal", skip_serializing_if = "Option::is_none")]
    pub can_appeal: Option<bool>,
}

impl PaFinalStatus {
    pub fn new() -> PaFinalStatus {
        PaFinalStatus {
            prior_authorization_status_type: None,
            closed_reason_code_id: None,
            authorization_number: None,
            authorization_period_start: None,
            authorization_period_end: None,
            pharmacy_type: None,
            quantity: None,
            days_supply: None,
            number_of_cycles: None,
            number_of_refills: None,
            note: None,
            can_appeal: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PriorAuthorizationStatusType {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Requested")]
    Requested,
    #[serde(rename = "NotRequired")]
    NotRequired,
    #[serde(rename = "Closed")]
    Closed,
    #[serde(rename = "Deferred")]
    Deferred,
    #[serde(rename = "ActionRequired")]
    ActionRequired,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Approved")]
    Approved,
    #[serde(rename = "Denied")]
    Denied,
    #[serde(rename = "AppealRequested")]
    AppealRequested,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "Canceled")]
    Canceled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "PartiallyDenied")]
    PartiallyDenied,
    #[serde(rename = "InProcess")]
    InProcess,
}

impl Default for PriorAuthorizationStatusType {
    fn default() -> PriorAuthorizationStatusType {
        Self::Unknown
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClosedReasonCodeId {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "ElectronicPriorAuthNotSupported")]
    ElectronicPriorAuthNotSupported,
    #[serde(rename = "Other")]
    Other,
    #[serde(rename = "PriorAuthNotRequired")]
    PriorAuthNotRequired,
    #[serde(rename = "CannotFindMatchingPatient")]
    CannotFindMatchingPatient,
    #[serde(rename = "PatientNotEligible")]
    PatientNotEligible,
    #[serde(rename = "PriorAuthDuplicateApproved")]
    PriorAuthDuplicateApproved,
    #[serde(rename = "PriorAuthDuplicateInProcess")]
    PriorAuthDuplicateInProcess,
    #[serde(rename = "ClosedByPayer")]
    ClosedByPayer,
    #[serde(rename = "ClosedByProvider")]
    ClosedByProvider,
    #[serde(rename = "ClosedByMember")]
    ClosedByMember,
    #[serde(rename = "AttachmentTypeNotSupported")]
    AttachmentTypeNotSupported,
    #[serde(rename = "PrescriberNotAllowedToSubmitPARequest")]
    PrescriberNotAllowedToSubmitPaRequest,
    #[serde(rename = "ResponseInconsistentWithQuestion")]
    ResponseInconsistentWithQuestion,
    #[serde(rename = "ReceiverNotPAProcessorForThisPatient")]
    ReceiverNotPaProcessorForThisPatient,
    #[serde(rename = "ReceiverNotPAProcessorForPatientMedicationCombo")]
    ReceiverNotPaProcessorForPatientMedicationCombo,
    #[serde(rename = "DuplicateDenied")]
    DuplicateDenied,
    #[serde(rename = "ProviderRespondedAfterDeadlineToReply")]
    ProviderRespondedAfterDeadlineToReply,
    #[serde(rename = "ProductNotCoveredByThisPlanPriorAuthorizationNotAvailable")]
    ProductNotCoveredByThisPlanPriorAuthorizationNotAvailable,
    #[serde(rename = "PrescriptionWithinPrescribingLimitsPriorAuthorizationNotRequiredForPatientMedication")]
    PrescriptionWithinPrescribingLimitsPriorAuthorizationNotRequiredForPatientMedication,
    #[serde(rename = "CoverageLimitsMayExistForQuantityAndOrDaysSupply")]
    CoverageLimitsMayExistForQuantityAndOrDaysSupply,
    #[serde(rename = "CoverageLimitsHaveBeenExceededExceptionNotAvailable")]
    CoverageLimitsHaveBeenExceededExceptionNotAvailable,
    #[serde(rename = "ActivePAOnFile")]
    ActivePaonFile,
    #[serde(rename = "SubmittedProductCodeIsNotValid")]
    SubmittedProductCodeIsNotValid,
}

impl Default for ClosedReasonCodeId {
    fn default() -> ClosedReasonCodeId {
        Self::Unknown
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PharmacyType {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Retail")]
    Retail,
    #[serde(rename = "MailOrder")]
    MailOrder,
    #[serde(rename = "SpecialtyPharmacy")]
    SpecialtyPharmacy,
    #[serde(rename = "LongTermCarePharmacy")]
    LongTermCarePharmacy,
    #[serde(rename = "Any")]
    Any,
    #[serde(rename = "TwentyFourHourPharmacy")]
    TwentyFourHourPharmacy,
    #[serde(rename = "FaxPharmacy")]
    FaxPharmacy,
    #[serde(rename = "EPCS")]
    Epcs,
    #[serde(rename = "InHouseDispensing")]
    InHouseDispensing,
    #[serde(rename = "Compounding")]
    Compounding,
    #[serde(rename = "DME")]
    Dme,
    #[serde(rename = "Kiosk")]
    Kiosk,
    #[serde(rename = "SupportsDigitalSignature")]
    SupportsDigitalSignature,
    #[serde(rename = "FaxPharmacyExternal")]
    FaxPharmacyExternal,
}

impl Default for PharmacyType {
    fn default() -> PharmacyType {
        Self::Unknown
    }
}

