/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthorizationAppealRequest {
    #[serde(rename = "AppealReason")]
    pub appeal_reason: String,
}

impl PriorAuthorizationAppealRequest {
    pub fn new(appeal_reason: String) -> PriorAuthorizationAppealRequest {
        PriorAuthorizationAppealRequest {
            appeal_reason,
        }
    }
}

