/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RtpsCoupon {
    #[serde(rename = "BIN", skip_serializing_if = "Option::is_none")]
    pub bin: Option<String>,
    #[serde(rename = "PCN", skip_serializing_if = "Option::is_none")]
    pub pcn: Option<String>,
    #[serde(rename = "MemberID", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    #[serde(rename = "GroupID", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
}

impl RtpsCoupon {
    pub fn new() -> RtpsCoupon {
        RtpsCoupon {
            bin: None,
            pcn: None,
            member_id: None,
            group_id: None,
        }
    }
}

