/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleSelfReportedMedicationRequest {
    #[serde(rename = "RoutedDoseFormDrugId")]
    pub routed_dose_form_drug_id: i32,
    #[serde(rename = "Refills", skip_serializing_if = "Option::is_none")]
    pub refills: Option<i32>,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "DispenseUnitId", skip_serializing_if = "Option::is_none")]
    pub dispense_unit_id: Option<i32>,
    #[serde(rename = "Quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "Directions", skip_serializing_if = "Option::is_none")]
    pub directions: Option<String>,
    #[serde(rename = "WrittenDate", skip_serializing_if = "Option::is_none")]
    pub written_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "PrescriberUserId", skip_serializing_if = "Option::is_none")]
    pub prescriber_user_id: Option<i32>,
    #[serde(rename = "PrescribingAgentUserId", skip_serializing_if = "Option::is_none")]
    pub prescribing_agent_user_id: Option<i32>,
    #[serde(rename = "InactiveDate", skip_serializing_if = "Option::is_none")]
    pub inactive_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Status")]
    pub status: Status,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "Encounter", skip_serializing_if = "Option::is_none")]
    pub encounter: Option<String>,
}

impl SimpleSelfReportedMedicationRequest {
    pub fn new(routed_dose_form_drug_id: i32, status: Status) -> SimpleSelfReportedMedicationRequest {
        SimpleSelfReportedMedicationRequest {
            routed_dose_form_drug_id,
            refills: None,
            days_supply: None,
            dispense_unit_id: None,
            quantity: None,
            directions: None,
            written_date: None,
            prescriber_user_id: None,
            prescribing_agent_user_id: None,
            inactive_date: None,
            status,
            comment: None,
            encounter: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Discontinued")]
    Discontinued,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "CancelPending")]
    CancelPending,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Changed")]
    Changed,
    #[serde(rename = "FullFill")]
    FullFill,
    #[serde(rename = "PartialFill")]
    PartialFill,
    #[serde(rename = "NoFill")]
    NoFill,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}

