/*
 * DoseSpot REST API - Plan: Jumpstart + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: JumpStart_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::jumpstart_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupervisorSnapshot {
    #[serde(rename = "FirstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "LastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "DEANumber", skip_serializing_if = "Option::is_none")]
    pub dea_number: Option<String>,
    #[serde(rename = "NPINumber", skip_serializing_if = "Option::is_none")]
    pub npi_number: Option<String>,
    #[serde(rename = "Address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::AddressSnapshot>>,
}

impl SupervisorSnapshot {
    pub fn new() -> SupervisorSnapshot {
        SupervisorSnapshot {
            first_name: None,
            last_name: None,
            dea_number: None,
            npi_number: None,
            address: None,
        }
    }
}

