/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianPrescriptionFavoriteCompiledCompoundRequest {
    #[serde(rename = "CompoundDescription")]
    pub compound_description: String,
    #[serde(rename = "CompoundIngredients")]
    pub compound_ingredients: Vec<models::CompoundIngredient>,
    #[serde(rename = "Refills")]
    pub refills: i32,
    #[serde(rename = "DaysSupply", skip_serializing_if = "Option::is_none")]
    pub days_supply: Option<i32>,
    #[serde(rename = "DispenseUnitTypeId")]
    pub dispense_unit_type_id: i32,
    #[serde(rename = "Quantity")]
    pub quantity: String,
    #[serde(rename = "NoSubstitutions", skip_serializing_if = "Option::is_none")]
    pub no_substitutions: Option<bool>,
    #[serde(rename = "Notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "Directions")]
    pub directions: String,
    #[serde(rename = "Title")]
    pub title: String,
    #[serde(rename = "FirstPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub first_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
    #[serde(rename = "SecondPrescriptionDiagnosis", skip_serializing_if = "Option::is_none")]
    pub second_prescription_diagnosis: Option<Box<models::PrescriptionDiagnosisIds>>,
}

impl ClinicianPrescriptionFavoriteCompiledCompoundRequest {
    pub fn new(compound_description: String, compound_ingredients: Vec<models::CompoundIngredient>, refills: i32, dispense_unit_type_id: i32, quantity: String, directions: String, title: String) -> ClinicianPrescriptionFavoriteCompiledCompoundRequest {
        ClinicianPrescriptionFavoriteCompiledCompoundRequest {
            compound_description,
            compound_ingredients,
            refills,
            days_supply: None,
            dispense_unit_type_id,
            quantity,
            no_substitutions: None,
            notes: None,
            directions,
            title,
            first_prescription_diagnosis: None,
            second_prescription_diagnosis: None,
        }
    }
}

