/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DrugInformation {
    #[serde(rename = "DispensableDrugId", skip_serializing_if = "Option::is_none")]
    pub dispensable_drug_id: Option<crate::ids::DispensableDrugId>,
    #[serde(rename = "RoutedDoseFormDrugId", skip_serializing_if = "Option::is_none")]
    pub routed_dose_form_drug_id: Option<i32>,
    #[serde(rename = "DrugName", skip_serializing_if = "Option::is_none")]
    pub drug_name: Option<String>,
}

impl DrugInformation {
    pub fn new() -> DrugInformation {
        DrugInformation {
            dispensable_drug_id: None,
            routed_dose_form_drug_id: None,
            drug_name: None,
        }
    }
}

