/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrescriptionBenefitsRequest {
    #[serde(rename = "Ndc")]
    pub ndc: String,
    #[serde(rename = "PharmacyId")]
    pub pharmacy_id: crate::ids::PharmacyId,
    #[serde(rename = "Quantity")]
    pub quantity: f64,
    #[serde(rename = "DaysSupply")]
    pub days_supply: i32,
    #[serde(rename = "DispenseUnitTypeID")]
    pub dispense_unit_type_id: i32,
    #[serde(rename = "PatientEligibilityId", skip_serializing_if = "Option::is_none")]
    pub patient_eligibility_id: Option<i32>,
}

impl GetPrescriptionBenefitsRequest {
    pub fn new(ndc: String, pharmacy_id: crate::ids::PharmacyId, quantity: f64, days_supply: i32, dispense_unit_type_id: i32) -> GetPrescriptionBenefitsRequest {
        GetPrescriptionBenefitsRequest {
            ndc,
            pharmacy_id,
            quantity,
            days_supply,
            dispense_unit_type_id,
            patient_eligibility_id: None,
        }
    }
}

