/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

/// ItemResponseSelfReportedMedicationResponse : Represents a generic response containing a single object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemResponseSelfReportedMedicationResponse {
    #[serde(rename = "Item", skip_serializing_if = "Option::is_none")]
    pub item: Option<Box<models::SelfReportedMedicationResponse>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ItemResponseSelfReportedMedicationResponse {
    /// Represents a generic response containing a single object.
    pub fn new() -> ItemResponseSelfReportedMedicationResponse {
        ItemResponseSelfReportedMedicationResponse {
            item: None,
            result: None,
        }
    }
}

