/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MedicationSearchRequest {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "DrugStatus", skip_serializing_if = "Option::is_none")]
    pub drug_status: Option<DrugStatus>,
}

impl MedicationSearchRequest {
    pub fn new(name: String) -> MedicationSearchRequest {
        MedicationSearchRequest {
            name,
            drug_status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DrugStatus {
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "All")]
    All,
}

impl Default for DrugStatus {
    fn default() -> DrugStatus {
        Self::Active
    }
}

