/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

/// MergePatientsRequest : Represents a request to merge two patients.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MergePatientsRequest {
    /// The patient identifier to merge from.
    #[serde(rename = "FromPatientId")]
    pub from_patient_id: crate::ids::PatientId,
    /// The patient identifier to merge to.
    #[serde(rename = "ToPatientId")]
    pub to_patient_id: crate::ids::PatientId,
    /// Indicates whether to merge allergies from the source patient to the target patient.  Default is false for backwards compatibility.
    #[serde(rename = "MergeAllergies", skip_serializing_if = "Option::is_none")]
    pub merge_allergies: Option<bool>,
}

impl MergePatientsRequest {
    /// Represents a request to merge two patients.
    pub fn new(from_patient_id: crate::ids::PatientId, to_patient_id: crate::ids::PatientId) -> MergePatientsRequest {
        MergePatientsRequest {
            from_patient_id,
            to_patient_id,
            merge_allergies: None,
        }
    }
}

