/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderSetResponse {
    #[serde(rename = "OrderSetId", skip_serializing_if = "Option::is_none")]
    pub order_set_id: Option<crate::ids::OrderSetId>,
    #[serde(rename = "Title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "Favorites", skip_serializing_if = "Option::is_none")]
    pub favorites: Option<Vec<models::ClinicianFavoritePrescriptionResponse>>,
}

impl OrderSetResponse {
    pub fn new() -> OrderSetResponse {
        OrderSetResponse {
            order_set_id: None,
            title: None,
            favorites: None,
        }
    }
}

