/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatientSpecificPricingCoverage {
    #[serde(rename = "Pharmacy", skip_serializing_if = "Option::is_none")]
    pub pharmacy: Option<Box<models::PrescriptionBenefitsPharmacy>>,
    #[serde(rename = "PricingCoverage", skip_serializing_if = "Option::is_none")]
    pub pricing_coverage: Option<Box<models::PricingCoverageFactors>>,
}

impl PatientSpecificPricingCoverage {
    pub fn new() -> PatientSpecificPricingCoverage {
        PatientSpecificPricingCoverage {
            pharmacy: None,
            pricing_coverage: None,
        }
    }
}

