/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrescriberInfoResponse {
    #[serde(rename = "Prescriber", skip_serializing_if = "Option::is_none")]
    pub prescriber: Option<Box<models::PrescriberInfo>>,
    #[serde(rename = "PrescriberAgent", skip_serializing_if = "Option::is_none")]
    pub prescriber_agent: Option<Box<models::PrescriberAgentInfo>>,
    #[serde(rename = "Supervisor", skip_serializing_if = "Option::is_none")]
    pub supervisor: Option<Box<models::PrescriberInfo>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl PrescriberInfoResponse {
    pub fn new() -> PrescriberInfoResponse {
        PrescriberInfoResponse {
            prescriber: None,
            prescriber_agent: None,
            supervisor: None,
            result: None,
        }
    }
}

