/*
 * DoseSpot REST API - Plan: Hybrid - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: HybridV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::hybrid::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransmissionErrors {
    #[serde(rename = "PrescriptionId", skip_serializing_if = "Option::is_none")]
    pub prescription_id: Option<crate::ids::PrescriptionId>,
    #[serde(rename = "DateWritten", skip_serializing_if = "Option::is_none")]
    pub date_written: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ErrorDateTimeStamp", skip_serializing_if = "Option::is_none")]
    pub error_date_time_stamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ErrorDetails", skip_serializing_if = "Option::is_none")]
    pub error_details: Option<String>,
    #[serde(rename = "PatientId", skip_serializing_if = "Option::is_none")]
    pub patient_id: Option<crate::ids::PatientId>,
    #[serde(rename = "ClinicId", skip_serializing_if = "Option::is_none")]
    pub clinic_id: Option<crate::ids::ClinicId>,
}

impl TransmissionErrors {
    pub fn new() -> TransmissionErrors {
        TransmissionErrors {
            prescription_id: None,
            date_written: None,
            error_date_time_stamp: None,
            error_details: None,
            patient_id: None,
            clinic_id: None,
        }
    }
}

