/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddEditClinicGroupRequest {
    #[serde(rename = "ClinicIds")]
    pub clinic_ids: Vec<i32>,
    #[serde(rename = "ClinicGroupName", skip_serializing_if = "Option::is_none")]
    pub clinic_group_name: Option<String>,
}

impl AddEditClinicGroupRequest {
    pub fn new(clinic_ids: Vec<i32>) -> AddEditClinicGroupRequest {
        AddEditClinicGroupRequest {
            clinic_ids,
            clinic_group_name: None,
        }
    }
}

