/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddEditPatientPharmacyRequest {
    #[serde(rename = "PharmacyId", skip_serializing_if = "Option::is_none")]
    pub pharmacy_id: Option<crate::ids::PharmacyId>,
    #[serde(rename = "SetAsPrimary", skip_serializing_if = "Option::is_none")]
    pub set_as_primary: Option<bool>,
}

impl AddEditPatientPharmacyRequest {
    pub fn new() -> AddEditPatientPharmacyRequest {
        AddEditPatientPharmacyRequest {
            pharmacy_id: None,
            set_as_primary: None,
        }
    }
}

