/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApproveRefillRequest {
    #[serde(rename = "Refills")]
    pub refills: i32,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "EffectiveDate", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub effective_date: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ApproveRefillRequest {
    pub fn new(refills: i32) -> ApproveRefillRequest {
        ApproveRefillRequest {
            refills,
            comment: None,
            effective_date: None,
        }
    }
}

