/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeRxChangePatientRequest {
    #[serde(rename = "PatientId")]
    pub patient_id: crate::ids::PatientId,
}

impl ChangeRxChangePatientRequest {
    pub fn new(patient_id: crate::ids::PatientId) -> ChangeRxChangePatientRequest {
        ChangeRxChangePatientRequest {
            patient_id,
        }
    }
}

