/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianReferenceNumberOverrides {
    #[serde(rename = "OverrideDeaNumber", skip_serializing_if = "Option::is_none")]
    pub override_dea_number: Option<String>,
    #[serde(rename = "OverrideSupervisorDeaNumber", skip_serializing_if = "Option::is_none")]
    pub override_supervisor_dea_number: Option<String>,
}

impl ClinicianReferenceNumberOverrides {
    pub fn new() -> ClinicianReferenceNumberOverrides {
        ClinicianReferenceNumberOverrides {
            override_dea_number: None,
            override_supervisor_dea_number: None,
        }
    }
}

