/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

/// ClinicianIdentityProofingRequest : represent a request to clinican identity proof
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianIdentityProofingRequest {
    #[serde(rename = "FirstName")]
    pub first_name: String,
    #[serde(rename = "MiddleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    #[serde(rename = "LastName")]
    pub last_name: String,
    #[serde(rename = "HomeAddress")]
    pub home_address: String,
    #[serde(rename = "City")]
    pub city: String,
    #[serde(rename = "State")]
    pub state: String,
    #[serde(rename = "ZipCode")]
    pub zip_code: String,
    #[serde(rename = "DateOfBirth", deserialize_with = "crate::datetime::deserialize")]
    pub date_of_birth: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "SocialSecurityNumber", skip_serializing_if = "Option::is_none")]
    pub social_security_number: Option<String>,
    #[serde(rename = "CreditCardNumber")]
    pub credit_card_number: String,
    #[serde(rename = "DrivingLicenseNumber", skip_serializing_if = "Option::is_none")]
    pub driving_license_number: Option<String>,
    #[serde(rename = "DrivingLicenseNumberState", skip_serializing_if = "Option::is_none")]
    pub driving_license_number_state: Option<String>,
    #[serde(rename = "PhoneNumber")]
    pub phone_number: String,
    #[serde(rename = "IsMobileNumber")]
    pub is_mobile_number: bool,
}

impl ClinicianIdentityProofingRequest {
    /// represent a request to clinican identity proof
    pub fn new(first_name: String, last_name: String, home_address: String, city: String, state: String, zip_code: String, date_of_birth: chrono::DateTime<chrono::FixedOffset>, credit_card_number: String, phone_number: String, is_mobile_number: bool) -> ClinicianIdentityProofingRequest {
        ClinicianIdentityProofingRequest {
            first_name,
            middle_name: None,
            last_name,
            home_address,
            city,
            state,
            zip_code,
            date_of_birth,
            social_security_number: None,
            credit_card_number,
            driving_license_number: None,
            driving_license_number_state: None,
            phone_number,
            is_mobile_number,
        }
    }
}

