/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicOrderSetResponse {
    /// Gets or sets the unique identifier for the order set.
    #[serde(rename = "OrderSetId", skip_serializing_if = "Option::is_none")]
    pub order_set_id: Option<crate::ids::OrderSetId>,
    /// Gets or sets the title of the order set.
    #[serde(rename = "Title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Gets or sets the list of favorite prescriptions associated with this order set.
    #[serde(rename = "Favorites", skip_serializing_if = "Option::is_none")]
    pub favorites: Option<Vec<models::ClinicFavoritePrescriptionResponse>>,
}

impl ClinicOrderSetResponse {
    pub fn new() -> ClinicOrderSetResponse {
        ClinicOrderSetResponse {
            order_set_id: None,
            title: None,
            favorites: None,
        }
    }
}

