/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopyPrescriptionRequest {
    #[serde(rename = "NewEffectiveDate", skip_serializing_if = "Option::is_none")]
    pub new_effective_date: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl CopyPrescriptionRequest {
    pub fn new() -> CopyPrescriptionRequest {
        CopyPrescriptionRequest {
            new_effective_date: None,
        }
    }
}

