/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteClinicianSupervisorRequest {
    #[serde(rename = "ClinicIds")]
    pub clinic_ids: Vec<i32>,
}

impl DeleteClinicianSupervisorRequest {
    pub fn new(clinic_ids: Vec<i32>) -> DeleteClinicianSupervisorRequest {
        DeleteClinicianSupervisorRequest {
            clinic_ids,
        }
    }
}

