/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DenyRefillRequest {
    #[serde(rename = "DenialReason")]
    pub denial_reason: DenialReason,
    #[serde(rename = "Note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl DenyRefillRequest {
    pub fn new(denial_reason: DenialReason) -> DenyRefillRequest {
        DenyRefillRequest {
            denial_reason,
            note: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DenialReason {
    #[serde(rename = "DeniedPatientUnknown")]
    DeniedPatientUnknown,
    #[serde(rename = "DeniedPatientNotUnderCare")]
    DeniedPatientNotUnderCare,
    #[serde(rename = "DeniedPatientNoLongerUnderPatientCare")]
    DeniedPatientNoLongerUnderPatientCare,
    #[serde(rename = "DeniedTooSoon")]
    DeniedTooSoon,
    #[serde(rename = "DeniedNeverPrescribed")]
    DeniedNeverPrescribed,
    #[serde(rename = "DeniedHavePatientContact")]
    DeniedHavePatientContact,
    #[serde(rename = "DeniedRefillInappropriate")]
    DeniedRefillInappropriate,
    #[serde(rename = "DeniedAlreadyPickedUp")]
    DeniedAlreadyPickedUp,
    #[serde(rename = "DeniedAlreadyPickedUpPartialFill")]
    DeniedAlreadyPickedUpPartialFill,
    #[serde(rename = "DeniedNotPickedUp")]
    DeniedNotPickedUp,
    #[serde(rename = "DeniedChangeInappropriate")]
    DeniedChangeInappropriate,
    #[serde(rename = "DeniedNeedAppointment")]
    DeniedNeedAppointment,
    #[serde(rename = "DeniedPrescriberNotAssociateWithLocation")]
    DeniedPrescriberNotAssociateWithLocation,
    #[serde(rename = "DeniedNoPriorAuthAttempt")]
    DeniedNoPriorAuthAttempt,
    #[serde(rename = "DeniedAlreadyHandled")]
    DeniedAlreadyHandled,
    #[serde(rename = "DeniedAtPatientRequest")]
    DeniedAtPatientRequest,
    #[serde(rename = "DeniedPatientAllergicToRequestMed")]
    DeniedPatientAllergicToRequestMed,
    #[serde(rename = "DeniedMedicationDiscontinued")]
    DeniedMedicationDiscontinued,
}

impl Default for DenialReason {
    fn default() -> DenialReason {
        Self::DeniedPatientUnknown
    }
}

