/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EpcsSuggestions {
    #[serde(rename = "SuggestedDeaNumber", skip_serializing_if = "Option::is_none")]
    pub suggested_dea_number: Option<Box<models::DeaNumber>>,
    #[serde(rename = "SuggestedSupervisorDeaNumber", skip_serializing_if = "Option::is_none")]
    pub suggested_supervisor_dea_number: Option<Box<models::DeaNumber>>,
    #[serde(rename = "Schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<models::ScheduleInfo>>,
}

impl EpcsSuggestions {
    pub fn new() -> EpcsSuggestions {
        EpcsSuggestions {
            suggested_dea_number: None,
            suggested_supervisor_dea_number: None,
            schedule: None,
        }
    }
}

