/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

/// ItemResponseDateTime : Represents a generic response containing a single object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemResponseDateTime {
    /// The response object.
    #[serde(rename = "Item", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub item: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ItemResponseDateTime {
    /// Represents a generic response containing a single object.
    pub fn new() -> ItemResponseDateTime {
        ItemResponseDateTime {
            item: None,
            result: None,
        }
    }
}

