/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

/// ListResponseClinic : Represents a generic response containing a list of objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponseClinic {
    /// The list of elements to return.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::Clinic>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ListResponseClinic {
    /// Represents a generic response containing a list of objects.
    pub fn new() -> ListResponseClinic {
        ListResponseClinic {
            items: None,
            result: None,
        }
    }
}

