/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MedicationHistoryRequest {
    #[serde(rename = "Start", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub start: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "End", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub end: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
}

impl MedicationHistoryRequest {
    pub fn new() -> MedicationHistoryRequest {
        MedicationHistoryRequest {
            start: None,
            end: None,
            page_number: None,
        }
    }
}

