/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NarxResponse {
    #[serde(rename = "HasReport", skip_serializing_if = "Option::is_none")]
    pub has_report: Option<bool>,
    #[serde(rename = "SoftErrorMessages", skip_serializing_if = "Option::is_none")]
    pub soft_error_messages: Option<Vec<models::KeyValuePairStringCommaString>>,
    #[serde(rename = "DisallowedMessages", skip_serializing_if = "Option::is_none")]
    pub disallowed_messages: Option<Vec<models::KeyValuePairStringCommaString>>,
    #[serde(rename = "Disclaimer", skip_serializing_if = "Option::is_none")]
    pub disclaimer: Option<String>,
    #[serde(rename = "ReportStates", skip_serializing_if = "Option::is_none")]
    pub report_states: Option<Vec<String>>,
    #[serde(rename = "ReportStatesMessage", skip_serializing_if = "Option::is_none")]
    pub report_states_message: Option<String>,
    #[serde(rename = "NarxScores", skip_serializing_if = "Option::is_none")]
    pub narx_scores: Option<Vec<models::KeyValuePairStringCommaString>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl NarxResponse {
    pub fn new() -> NarxResponse {
        NarxResponse {
            has_report: None,
            soft_error_messages: None,
            disallowed_messages: None,
            disclaimer: None,
            report_states: None,
            report_states_message: None,
            narx_scores: None,
            result: None,
        }
    }
}

