/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaCancelDetails {
    #[serde(rename = "CancelReason", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<String>,
}

impl PaCancelDetails {
    pub fn new() -> PaCancelDetails {
        PaCancelDetails {
            cancel_reason: None,
        }
    }
}

