/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaHistoryQuestionSet {
    #[serde(rename = "PriorAuthorizationQuestionSetId", skip_serializing_if = "Option::is_none")]
    pub prior_authorization_question_set_id: Option<i32>,
    #[serde(rename = "QuestionSetAlias", skip_serializing_if = "Option::is_none")]
    pub question_set_alias: Option<String>,
    #[serde(rename = "Title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "AnsweredQuestions", skip_serializing_if = "Option::is_none")]
    pub answered_questions: Option<Vec<models::PaAnsweredQuestions>>,
    #[serde(rename = "Attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::PaAttachment>>,
}

impl PaHistoryQuestionSet {
    pub fn new() -> PaHistoryQuestionSet {
        PaHistoryQuestionSet {
            prior_authorization_question_set_id: None,
            question_set_alias: None,
            title: None,
            answered_questions: None,
            attachments: None,
        }
    }
}

