/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaStatusLog {
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "AdditionalInfoAttachmentId", skip_serializing_if = "Option::is_none")]
    pub additional_info_attachment_id: Option<i32>,
    #[serde(rename = "AdditionalInfo", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
    #[serde(rename = "CreatedDateStamp", skip_serializing_if = "Option::is_none")]
    pub created_date_stamp: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl PaStatusLog {
    pub fn new() -> PaStatusLog {
        PaStatusLog {
            status: None,
            additional_info_attachment_id: None,
            additional_info: None,
            created_date_stamp: None,
        }
    }
}

