/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedListResponsePrescription {
    /// The list of elements to return.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::Prescription>>,
    #[serde(rename = "PageResult", skip_serializing_if = "Option::is_none")]
    pub page_result: Option<Box<models::PageResult>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl PagedListResponsePrescription {
    pub fn new() -> PagedListResponsePrescription {
        PagedListResponsePrescription {
            items: None,
            page_result: None,
            result: None,
        }
    }
}

