/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmpResponse {
    #[serde(rename = "StateId", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<i32>,
    #[serde(rename = "ProgramName", skip_serializing_if = "Option::is_none")]
    pub program_name: Option<String>,
    #[serde(rename = "URL", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "Message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PdmpResponse {
    pub fn new() -> PdmpResponse {
        PdmpResponse {
            state_id: None,
            program_name: None,
            url: None,
            message: None,
        }
    }
}

