/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthAnswerRequest {
    #[serde(rename = "PriorAuthorizationQuestionChoices", skip_serializing_if = "Option::is_none")]
    pub prior_authorization_question_choices: Option<Vec<models::PriorAuthorizationChoiceAnswer>>,
    #[serde(rename = "DateTimeAnswer", skip_serializing_if = "Option::is_none")]
    pub date_time_answer: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "NumericAnswer", skip_serializing_if = "Option::is_none")]
    pub numeric_answer: Option<f64>,
    #[serde(rename = "FreeTextAnswer", skip_serializing_if = "Option::is_none")]
    pub free_text_answer: Option<String>,
}

impl PriorAuthAnswerRequest {
    pub fn new() -> PriorAuthAnswerRequest {
        PriorAuthAnswerRequest {
            prior_authorization_question_choices: None,
            date_time_answer: None,
            numeric_answer: None,
            free_text_answer: None,
        }
    }
}

