/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuantityLimitRestriction {
    #[serde(rename = "MaximumAmount", skip_serializing_if = "Option::is_none")]
    pub maximum_amount: Option<f64>,
    #[serde(rename = "AmountUnit", skip_serializing_if = "Option::is_none")]
    pub amount_unit: Option<AmountUnit>,
    #[serde(rename = "TimePeriodUnit", skip_serializing_if = "Option::is_none")]
    pub time_period_unit: Option<TimePeriodUnit>,
    #[serde(rename = "StartDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "EndDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "MaximumTimePeriodUnits", skip_serializing_if = "Option::is_none")]
    pub maximum_time_period_units: Option<i32>,
}

impl QuantityLimitRestriction {
    pub fn new() -> QuantityLimitRestriction {
        QuantityLimitRestriction {
            maximum_amount: None,
            amount_unit: None,
            time_period_unit: None,
            start_date: None,
            end_date: None,
            maximum_time_period_units: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountUnit {
    #[serde(rename = "DollarAmount")]
    DollarAmount,
    #[serde(rename = "DaysSupply")]
    DaysSupply,
    #[serde(rename = "Fills")]
    Fills,
    #[serde(rename = "Quantity")]
    Quantity,
}

impl Default for AmountUnit {
    fn default() -> AmountUnit {
        Self::DollarAmount
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimePeriodUnit {
    #[serde(rename = "Days")]
    Days,
    #[serde(rename = "Lifetime")]
    Lifetime,
    #[serde(rename = "PerDispensing")]
    PerDispensing,
    #[serde(rename = "SpecificDateRange")]
    SpecificDateRange,
    #[serde(rename = "CalendarYear")]
    CalendarYear,
    #[serde(rename = "CalendarQuarter")]
    CalendarQuarter,
    #[serde(rename = "CalendarMonth")]
    CalendarMonth,
}

impl Default for TimePeriodUnit {
    fn default() -> TimePeriodUnit {
        Self::Days
    }
}

