/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

/// SearchPatientDiagnosesRequest : Request to search a patient's active diagnoses by ICD code or description.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchPatientDiagnosesRequest {
    /// The term to search for, matched against the diagnosis's ICD code or description. Required, 3-100 characters.
    #[serde(rename = "SearchTerm")]
    pub search_term: String,
    /// The page number, defaults to 1. Must be between 1 and 1000.
    #[serde(rename = "PageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
}

impl SearchPatientDiagnosesRequest {
    /// Request to search a patient's active diagnoses by ICD code or description.
    pub fn new(search_term: String) -> SearchPatientDiagnosesRequest {
        SearchPatientDiagnosesRequest {
            search_term,
            page_number: None,
        }
    }
}

