/*
 * DoseSpot REST API - Plan: Full + EPCS - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Full_EPCSV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::full_epcs::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSelfReportedMedicationStatusRequest {
    #[serde(rename = "InactiveDate", skip_serializing_if = "Option::is_none")]
    pub inactive_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "Status")]
    pub status: Status,
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "Encounter", skip_serializing_if = "Option::is_none")]
    pub encounter: Option<String>,
}

impl UpdateSelfReportedMedicationStatusRequest {
    pub fn new(status: Status) -> UpdateSelfReportedMedicationStatusRequest {
        UpdateSelfReportedMedicationStatusRequest {
            inactive_date: None,
            status,
            comment: None,
            encounter: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Discontinued")]
    Discontinued,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "CancelPending")]
    CancelPending,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Changed")]
    Changed,
    #[serde(rename = "FullFill")]
    FullFill,
    #[serde(rename = "PartialFill")]
    PartialFill,
    #[serde(rename = "NoFill")]
    NoFill,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}

