/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClinicianIdentityProofingDisclaimerResponse {
    #[serde(rename = "IdpDisclaimerDate", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::datetime::deserialize_option")]
    pub idp_disclaimer_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "IdpDisclaimerId", skip_serializing_if = "Option::is_none")]
    pub idp_disclaimer_id: Option<i32>,
    #[serde(rename = "IdpDisclaimerText", skip_serializing_if = "Option::is_none")]
    pub idp_disclaimer_text: Option<String>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ClinicianIdentityProofingDisclaimerResponse {
    pub fn new() -> ClinicianIdentityProofingDisclaimerResponse {
        ClinicianIdentityProofingDisclaimerResponse {
            idp_disclaimer_date: None,
            idp_disclaimer_id: None,
            idp_disclaimer_text: None,
            result: None,
        }
    }
}

