/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenderLimitRestriction {
    #[serde(rename = "GenderAbbreviation", skip_serializing_if = "Option::is_none")]
    pub gender_abbreviation: Option<String>,
    #[serde(rename = "GenderDescription", skip_serializing_if = "Option::is_none")]
    pub gender_description: Option<String>,
}

impl GenderLimitRestriction {
    pub fn new() -> GenderLimitRestriction {
        GenderLimitRestriction {
            gender_abbreviation: None,
            gender_description: None,
        }
    }
}

