/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

/// ListResponseStandardDispenseUnitType : Represents a generic response containing a list of objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponseStandardDispenseUnitType {
    /// The list of elements to return.
    #[serde(rename = "Items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::StandardDispenseUnitType>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl ListResponseStandardDispenseUnitType {
    /// Represents a generic response containing a list of objects.
    pub fn new() -> ListResponseStandardDispenseUnitType {
        ListResponseStandardDispenseUnitType {
            items: None,
            result: None,
        }
    }
}

