/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MedicationCoverageRequest {
    #[serde(rename = "PatientEligibilityId")]
    pub patient_eligibility_id: i32,
    #[serde(rename = "NDC")]
    pub ndc: String,
}

impl MedicationCoverageRequest {
    pub fn new(patient_eligibility_id: i32, ndc: String) -> MedicationCoverageRequest {
        MedicationCoverageRequest {
            patient_eligibility_id,
            ndc,
        }
    }
}

