/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrescriptionLog {
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "DateTimeStamp", skip_serializing_if = "Option::is_none")]
    pub date_time_stamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "AdditionalInfo", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
    #[serde(rename = "Ignored", skip_serializing_if = "Option::is_none")]
    pub ignored: Option<bool>,
    #[serde(rename = "User", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    #[serde(rename = "WasRefillRequest", skip_serializing_if = "Option::is_none")]
    pub was_refill_request: Option<bool>,
    #[serde(rename = "MedicationStatus", skip_serializing_if = "Option::is_none")]
    pub medication_status: Option<MedicationStatus>,
}

impl PrescriptionLog {
    pub fn new() -> PrescriptionLog {
        PrescriptionLog {
            status: None,
            date_time_stamp: None,
            additional_info: None,
            ignored: None,
            user: None,
            was_refill_request: None,
            medication_status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Entered")]
    Entered,
    #[serde(rename = "Printed")]
    Printed,
    #[serde(rename = "Sending")]
    Sending,
    #[serde(rename = "eRxSent")]
    ERxSent,
    #[serde(rename = "FaxSent")]
    FaxSent,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Requested")]
    Requested,
    #[serde(rename = "Edited")]
    Edited,
    #[serde(rename = "EpcsError")]
    EpcsError,
    #[serde(rename = "EpcsSigned")]
    EpcsSigned,
    #[serde(rename = "ReadyToSign")]
    ReadyToSign,
    #[serde(rename = "PharmacyVerified")]
    PharmacyVerified,
    #[serde(rename = "PharmacySelect")]
    PharmacySelect,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MedicationStatus {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Inactive")]
    Inactive,
    #[serde(rename = "Discontinued")]
    Discontinued,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CancelRequested")]
    CancelRequested,
    #[serde(rename = "CancelPending")]
    CancelPending,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "CancelDenied")]
    CancelDenied,
    #[serde(rename = "Changed")]
    Changed,
    #[serde(rename = "FullFill")]
    FullFill,
    #[serde(rename = "PartialFill")]
    PartialFill,
    #[serde(rename = "NoFill")]
    NoFill,
}

impl Default for MedicationStatus {
    fn default() -> MedicationStatus {
        Self::Unknown
    }
}

