/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrescriptionDiagnosis {
    #[serde(rename = "PrimaryDiagnosis", skip_serializing_if = "Option::is_none")]
    pub primary_diagnosis: Option<Box<models::Diagnosis>>,
    #[serde(rename = "SecondaryDiagnosis", skip_serializing_if = "Option::is_none")]
    pub secondary_diagnosis: Option<Box<models::Diagnosis>>,
}

impl PrescriptionDiagnosis {
    pub fn new() -> PrescriptionDiagnosis {
        PrescriptionDiagnosis {
            primary_diagnosis: None,
            secondary_diagnosis: None,
        }
    }
}

