/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorAuthorizationStatusLogUiResponse {
    #[serde(rename = "StatusLog", skip_serializing_if = "Option::is_none")]
    pub status_log: Option<Vec<models::PriorAuthStatusLogUi>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl PriorAuthorizationStatusLogUiResponse {
    pub fn new() -> PriorAuthorizationStatusLogUiResponse {
        PriorAuthorizationStatusLogUiResponse {
            status_log: None,
            result: None,
        }
    }
}

