/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

/// Response : The result of the operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Response {
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::Result>>,
}

impl Response {
    /// The result of the operation.
    pub fn new() -> Response {
        Response {
            result: None,
        }
    }
}

