/*
 * DoseSpot REST API - Plan: Read Only - V2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: ReadOnlyV2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::readonly::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TherapeuticAlternatives {
    #[serde(rename = "Ndc", skip_serializing_if = "Option::is_none")]
    pub ndc: Option<String>,
    #[serde(rename = "FormularyStatus", skip_serializing_if = "Option::is_none")]
    pub formulary_status: Option<String>,
    #[serde(rename = "Copay", skip_serializing_if = "Option::is_none")]
    pub copay: Option<Box<models::PayerCopay>>,
    #[serde(rename = "DisplayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "FormularyInfo", skip_serializing_if = "Option::is_none")]
    pub formulary_info: Option<Box<models::FormularyInfo>>,
    #[serde(rename = "FullDisplayString", skip_serializing_if = "Option::is_none")]
    pub full_display_string: Option<String>,
    #[serde(rename = "DisplayStrength", skip_serializing_if = "Option::is_none")]
    pub display_strength: Option<String>,
    #[serde(rename = "DefaultDispenseUnitID", skip_serializing_if = "Option::is_none")]
    pub default_dispense_unit_id: Option<i32>,
    #[serde(rename = "DispensableDrugId", skip_serializing_if = "Option::is_none")]
    pub dispensable_drug_id: Option<crate::ids::DispensableDrugId>,
    #[serde(rename = "Schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<i32>,
    #[serde(rename = "IsDetox", skip_serializing_if = "Option::is_none")]
    pub is_detox: Option<bool>,
    #[serde(rename = "HasGHB", skip_serializing_if = "Option::is_none")]
    pub has_ghb: Option<bool>,
    #[serde(rename = "RxCUI", skip_serializing_if = "Option::is_none")]
    pub rx_cui: Option<i32>,
}

impl TherapeuticAlternatives {
    pub fn new() -> TherapeuticAlternatives {
        TherapeuticAlternatives {
            ndc: None,
            formulary_status: None,
            copay: None,
            display_name: None,
            formulary_info: None,
            full_display_string: None,
            display_strength: None,
            default_dispense_unit_id: None,
            dispensable_drug_id: None,
            schedule: None,
            is_detox: None,
            has_ghb: None,
            rx_cui: None,
        }
    }
}

